Repository MycroftAI/mycroft-core, pull requests merged in 2018-10, with the labels that each got.

#1827 Fix date format for today/tomorrow/yesterday
  mycroft/skills/core.py
  mycroft/util/format.py
Labels: CLA: Yes

#1818 Use the phonetic_spellings.txt in Mimic2
  mycroft/res/text/en-us/phonetic_spellings.txt
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes, Enhancement

#1825 Add protection for naive skill authors
  mycroft/client/text/text_client.py
  mycroft/skills/core.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#1828 Make the combo lock handle multiple users
  mycroft/util/combo_lock.py
Labels: CLA: Yes, type: bug

#1833 Workaround for get-pip issue
  dev_setup.sh
Labels: CLA: Yes

#1815 feature: allow adapt context across skills
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  test/unittests/skills/test_core.py
Labels: CLA: Yes

#1841 Pronounce large numbers, Bugfix/ issue 1718
  mycroft/util/lang/format_en.py
  test/unittests/util/test_format.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes, type: bug

#1831 Language error checking
  mycroft/util/parse.py
Labels: CLA: Yes

#1842 Add module specific lang option to GoogleCloudStt
  mycroft/stt/__init__.py
Labels: CLA: Yes, tagged for review and potential merge

#1835 Cleanup of core.py
  mycroft/skills/core.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1837 centos support
  dev_setup.sh
Labels: CLA: Yes, platform: centos

#1843 Add CommonPlaySkill, unifying search and control
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes, tagged for review and potential merge

#1847 Add support for comment lines in dialog files
  mycroft/dialog/__init__.py
Labels: CLA: Yes, type: translation

#1852 Add check separating centOS and Fedora
  dev_setup.sh
Labels: CLA: Yes, platform: fedora, type: bug

#1856 Feature/rhel
  dev_setup.sh
Labels: CLA: Yes

#1834 Replace hard coded data directory path in echo
  scripts/prepare-msm.sh
Labels: CLA: Yes
