Repository MycroftAI/mycroft-core, pull requests merged in 2018-07, with the labels that each got.

#1670 Bugfix/parse corrections
  mycroft/util/lang/parse_en.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1661 Update requests to bleeding edge
  requirements.txt
Labels: CLA: Yes, platform: mark1, platform: picroft

#1565 Feature add responsive voice tts
  mycroft/configuration/mycroft.conf
  mycroft/tts/__init__.py
  mycroft/tts/responsive_voice_tts.py
Labels: CLA: Yes, tagged for review and potential merge

#1668 Enhance the behavior of the Mark 1 button
  mycroft/audio/speech.py
  mycroft/client/enclosure/__init__.py
  mycroft/skills/core.py
  mycroft/tts/__init__.py
Labels: CLA: Yes, tagged for review and potential merge

#1657 Refactor Precise engine and support engine timeouts
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
  requirements.txt
Labels: CLA: Yes, status: waiting for fix, type: Code Improvements / Refactor

#1675 Fix crash during initial skill download
  mycroft/skills/main.py
Labels: CLA: Yes, type: bug

#1663 feature/allow to pronounce ordinals and very small fractions
  mycroft/util/lang/parse_en.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1680 Remove stray lock.release()
  mycroft/audio/speech.py
Labels: CLA: Yes, type: bug

#1682 Add 'venv-activate.sh' script
  venv-activate.sh
Labels: CLA: Yes

#1667 CLI Updates: Restore VT100 support, help, etc.
  mycroft/client/text/main.py
Labels: CLA: Yes, status: waiting for fix, tagged for review and potential merge

#1685 allow disabling intent in initialize
  mycroft/skills/core.py
Labels: CLA: Yes

#1686 padatious enable/disable
  mycroft/skills/core.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#1684 MAXCORES bug fix in dev_setup.sh
  dev_setup.sh
Labels: CLA: Yes

#1671 Fix startup of audio-test
  start-mycroft.sh
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1687 Clean up setup scripts
  .gitignore
  MANIFEST.in
  mycroft-base-setup.py
  mycroft/metrics/__init__.py
  mycroft/skills/container.py
  mycroft/util/setup_base.py
  setup.py
  skills-sdk-MANIFEST.in
  skills-sdk-setup.py
  start-mycroft.sh
Labels: CLA: Yes, type: Code Improvements / Refactor

#1688 Bugfix/unmunge
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1648 Update default config for skills
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1683 Improve the standalone skill tester
  test/integrationtests/skills/discover_tests.py
  test/integrationtests/skills/runner.py
  test/integrationtests/skills/skill_developers_testrunner.py
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, DOC: Update required, tagged for review and potential merge

#1690 Add new MycroftSkill.ask_yesno() method
  mycroft/res/text/en-us/no.voc
  mycroft/res/text/en-us/yes.voc
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1669 German formatting for Wolfram alpha skill responses in format_de.py
  mycroft/res/text/de-de/cancel.voc
  mycroft/res/text/de-de/checking for updates.dialog
  mycroft/res/text/de-de/i didn't catch that.dialog
  mycroft/res/text/de-de/learning enabled.dialog
  mycroft/res/text/de-de/mycroft.intro.dialog
  mycroft/res/text/de-de/not connected to the internet.dialog
  mycroft/res/text/de-de/not.loaded.dialog
  mycroft/res/text/de-de/phonetic_spellings.txt
  mycroft/res/text/de-de/skills updated.dialog
  mycroft/res/text/de-de/sorry I couldn't install default skills.dialog
  mycroft/res/text/de-de/ssh disabled.dialog
  mycroft/res/text/de-de/ssh enabled.dialog
  mycroft/util/lang/format_de.py
  test/unittests/util/test_format_de.py
  test/unittests/util/test_parse_de.py
Labels: CLA: Yes

#1695 Allow reference dates with tzinfo
  mycroft/util/lang/parse_en.py
Labels: CLA: Yes, tagged for review and potential merge

#1698 Upgrade mycroft-authored dependencies
  requirements.txt
Labels: CLA: Yes

#1706 Immediately speak warning while Padatious trains
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#1703 Check if only python3 is installed in start-mycroft.sh script
  start-mycroft.sh
Labels: CLA: Yes

#1707 Add enclosure to the start/stop dev scripts
  start-mycroft.sh
  stop-mycroft.sh
Labels: CLA: Yes

#1705 Fix named event scheduling/deleting
  mycroft/skills/core.py
  mycroft/skills/event_scheduler.py
  test/unittests/skills/test_core.py
  test/unittests/util/test_parse_fr.py
Labels: CLA: Yes

#1704 Fix CLI screen corruption
  mycroft/client/text/main.py
Labels: CLA: Yes

#1653 Feature/pronounce scientific
  mycroft/util/format.py
  mycroft/util/lang/format_en.py
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_format.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes
