Repository MycroftAI/mycroft-core, pull requests merged in 2018-12, with the labels that each got.

#1901 Update padaos to better handle bad translations
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1890 Update gtts modules to fix google tts
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1900 Common query framework
  mycroft/skills/common_query_skill.py
Labels: CLA: Yes

#1894 Handle failing refresh tokens
  mycroft/api/__init__.py
Labels: CLA: Yes, type: bug

#1903 Handle invalid json when loading log level
  mycroft/util/log.py
Labels: CLA: Yes, type: bug

#1910 Italian minor update in res/text/it-it/
  mycroft/res/text/it-it/backend.down.dialog
  mycroft/res/text/it-it/no.voc
  mycroft/res/text/it-it/not connected to the internet.dialog
  mycroft/res/text/it-it/not.loaded.dialog
  mycroft/res/text/it-it/phonetic_spellings.txt
  mycroft/res/text/it-it/skill.error.dialog
  mycroft/res/text/it-it/yes.voc
Labels: CLA: Yes, type: translation

#1909 Stop hotword engines when reloading
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
Labels: CLA: Yes, type: bug

#1914 bugfix/issue-1913 fixed bug with new flag
  dev_setup.sh
Labels: CLA: Yes

#1915 Store config in more human readable form
  mycroft/configuration/config.py
Labels: CLA: Yes

#1916 Handle floats when checking year pronounciation
  mycroft/util/lang/format_en.py
Labels: CLA: Yes, type: bug

#1918 Add option to skip mimic build in dev_setup.sh
  dev_setup.sh
Labels: CLA: Yes

#1905 Add python 3.7 python version to travis tests
  .travis.yml
Labels: CLA: Yes, type: test

#1911 Minor update to dialog
  mycroft/dialog/__init__.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1920 Add basic barge-in functionality
  mycroft/client/speech/__main__.py
  mycroft/client/speech/listener.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#1922 GUI update
  mycroft/client/enclosure/base.py
  mycroft/client/enclosure/generic/__init__.py
  mycroft/client/text/gui_server.py
  mycroft/skills/core.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, type: feature

#1924 Improve setup and start-mycroft scripts
  .gitignore
  dev_setup.sh
  start-mycroft.sh
Labels: CLA: Yes
