Repository MycroftAI/mycroft-core, pull requests merged in 2018-08, with the labels that each got.

#1709 Upgrade padatious
  requirements.txt
Labels: CLA: Yes

#1710 Do not enter python virtual env when inside Docker container
  start-mycroft.sh
Labels: CLA: Yes

#1708 Feature/mimic2 visemse
  mycroft/configuration/mycroft.conf
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#1700 Replace static /opt/mycraft in prepare-msm.sh
  scripts/prepare-msm.sh
Labels: CLA: Yes

#1712 start-mycroft.sh improvements (change log dir and exit 1 when out of date)
  dev_setup.sh
  mycroft/client/text/main.py
  start-mycroft.sh
  stop-mycroft.sh
Labels: CLA: Yes

#1715 Remove git locks when starting mycroft
  mycroft/skills/main.py
Labels: CLA: Yes, type: bug

#1713 Allow Padatious to override Adapt
  mycroft/skills/intent_service.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#1727 Fix camel case splitting
  mycroft/skills/core.py
  mycroft/util/__init__.py
Labels: CLA: Yes

#1737 improved mimic2 to not speed talk on numbers
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#1721 remove isSpeaking signal on audio startup
  mycroft/audio/main.py
Labels: CLA: Yes

#1724 added isSpeaking Signal
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes, tagged for review and potential merge

#1738 Fix CLI lockup; simple 'speak' support; help display
  mycroft/client/text/main.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1740 better pronounciation for 4 digit numbers
  mycroft/util/lang/format_en.py
  test/unittests/util/test_format.py
Labels: CLA: Yes, tagged for review and potential merge

#1742 Handle remove_all_listeners
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug, type: test

#1743 Change to the supported wait_while_speaking()
  mycroft/client/enclosure/__init__.py
Labels: CLA: Yes, tagged for review and potential merge

#1729 Add retry limit for chromecast detection
  mycroft/audio/services/chromecast/__init__.py
Labels: CLA: Yes, tagged for review and potential merge

#1741 Upgrade msm to 0.5.18
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1720 Bugfix/write pho file
  mycroft/tts/__init__.py
  mycroft/tts/mimic_tts.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1745 Set default encoding in a cleaner way
  mycroft/client/text/main.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1744 Set the directory explicitly start-mycroft.sh scripts
  start-mycroft.sh
  stop-mycroft.sh
Labels: CLA: Yes, tagged for review and potential merge

#1748 restrict str.replace from doing a global string replacement
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes, type: bug

#1750 Fix removing scheduled events
  mycroft/skills/core.py
Labels: CLA: Yes, type: bug

#1752 Remove deprecated API.find*() methods
  mycroft/api/__init__.py
Labels: 18.08, CLA: Yes

#1755 Enhance tester output
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes

#1725 Feature/__main__
  mycroft/audio/__main__.py
  mycroft/audio/audioservice.py
  mycroft/client/enclosure/__main__.py
  mycroft/client/speech/__main__.py
  mycroft/client/text/__main__.py
  mycroft/client/text/text_client.py
  mycroft/messagebus/service/__main__.py
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
  setup.py
  start-mycroft.sh
  stop-mycroft.sh
  test/unittests/audio/test_service.py
Labels: 18.08, CLA: Yes, type: Code Improvements / Refactor

#1756 Remove deprecated extractnumber
  mycroft/util/__init__.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
  test/unittests/util/test_parse_de.py
  test/unittests/util/test_parse_fr.py
  test/unittests/util/test_parse_it.py
  test/unittests/util/test_parse_pt.py
  test/unittests/util/test_parse_sv.py
Labels: CLA: Yes

#1753 Add support for separate settings for test
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes

#1731 Remove depreciated ScheduledSkill
  mycroft/skills/scheduled_skills.py
  mycroft/skills/time_rules.py
  requirements.txt
  test/unittests/skills/test_scheduled_skills.py
Labels: 18.08, CLA: Yes

#1759 Fix skills listing
  mycroft/client/text/text_client.py
Labels: CLA: Yes

#1692 Make dialog loading more strict
  mycroft/dialog/__init__.py
Labels: CLA: Yes

#1719 add skill vocab to self.is_match
  mycroft/skills/core.py
Labels: CLA: Yes

#1758 Remove announcement parameter from get_response
  mycroft/skills/core.py
Labels: CLA: Yes

#1760 Separate enclosure api from enclosure client
  mycroft/client/enclosure/__init__.py
  mycroft/client/enclosure/mouth.py
  mycroft/client/enclosure/weather.py
  mycroft/client/speech/__main__.py
  mycroft/enclosure/__init__.py
  mycroft/enclosure/api.py
  mycroft/enclosure/display_manager.py
  mycroft/skills/__main__.py
  mycroft/skills/core.py
  mycroft/skills/skill_manager.py
  mycroft/tts/__init__.py
Labels: 18.08, CLA: Yes

#1766 Fix PEP8 issue created by accidental code merge
  mycroft/messagebus/client/ws.py
Labels: CLA: Yes

#1768 Remove trailing references to MycroftSkill.emitter
  mycroft/skills/core.py
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#1770 Address Python 3 changes
  mycroft/audio/services/mopidy/mopidypost.py
  test/unittests/client/test_dynamic_energy_test.py
Labels: CLA: Yes

#1767 Move Mark-1 specific image code from api to mark-1 enclosure
  mycroft/client/enclosure/mouth.py
  mycroft/enclosure/api.py
  mycroft/enclosure/display_manager.py
Labels: 18.08, CLA: Yes, platform: mark1

#1773 Fix path in recent locale support
  mycroft/dialog/__init__.py
  mycroft/skills/core.py
  mycroft/skills/skill_data.py
Labels: CLA: Yes

#1774 Bugfix/simple audioservice
  mycroft/audio/services/simple/__init__.py
Labels: 18.08, CLA: Yes, type: bug

#1775 Fix exception in exception handler
  mycroft/util/lang/format_en.py
Labels: CLA: Yes

#1776 Switch msm branch to 18.08
  mycroft/configuration/mycroft.conf
  requirements.txt
Labels: 18.08, CLA: Yes

#1778 Blacklist pianobar-skill
  mycroft/configuration/mycroft.conf
Labels: 18.08, CLA: Yes

#1779 Prepare version update to 18.8.0
  mycroft/version/__init__.py
Labels: 18.08, CLA: Yes
