Repository MycroftAI/mycroft-core, pull requests merged in 2018-11, with the labels that each got.

#1861 Update MycroftSkill api documentation
  doc/Makefile
  doc/README.md
  doc/conf.py
  doc/requirements.txt
  mycroft/skills/core.py
Labels: CLA: Yes, type: documentation

#1866 extract date time improvement/bugfix
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1869 Update mycroft.conf
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#1872 Update api documentation
  doc/generate_sdk_docs.py
  doc/source/mycroft.rst
  doc/source/mycroft.util.parse.rst
  doc/source/mycroft.util.rst
  mycroft/skills/common_play_skill.py
  mycroft/util/__init__.py
  start-mycroft.sh
  test-requirements.txt
Labels: CLA: Yes, type: documentation

#1864 Skilltester extension for Common Playback Skill functions
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, DOC: Update required, type: test

#1873 bugfix/utterance remainder, only replace complete words
  mycroft/messagebus/message.py
Labels: CLA: Yes, type: bug

#1870 improve datetime parsing
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes, type: feature

#1867 feature/extract multiple numbers from text
  mycroft/util/lang/parse_common.py
  mycroft/util/lang/parse_de.py
  mycroft/util/lang/parse_en.py
  mycroft/util/lang/parse_fr.py
  mycroft/util/lang/parse_it.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1871 Bugfix CPS Starting audio
  mycroft/audio/audioservice.py
Labels: CLA: Yes, type: bug

#1884 fix converse
  mycroft/skills/intent_service.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, type: bug, type: feature

#1886 include skill_id in response
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug, type: test

#1887 Upgrade msk to 0.3.12
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1879 Issue-1877 - fix ordinal followed by one
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1885 Feature/msm 0.6.2
  mycroft/skills/skill_manager.py
  requirements.txt
Labels: CLA: Yes, MSM
