Repository MycroftAI/mycroft-core, pull requests merged in 2018-04, with the labels that each got.

#1521 Default skill config to empty dict
  mycroft/skills/core.py
Labels: CLA: Yes

#1520 Feature/api etags
  mycroft/api/__init__.py
Labels: CLA: Yes

#1525 Fix error code 20 when doing msm default
  msm/msm
Labels: CLA: Yes, MSM, type: bug

#1523 Fix cancel_all_repeating_events()
  mycroft/skills/core.py
Labels: CLA: Yes, type: bug

#1528 Skill settings improvements
  mycroft/skills/core.py
  mycroft/skills/settings.py
Labels: CLA: Yes, type: feature

#1519 Shutdown improvements
  mycroft/audio/main.py
  mycroft/audio/speech.py
  mycroft/client/speech/main.py
  mycroft/lock/__init__.py
  mycroft/messagebus/client/ws.py
  mycroft/messagebus/service/main.py
  mycroft/skills/container.py
  mycroft/skills/core.py
  mycroft/skills/main.py
  mycroft/util/__init__.py
  stop-mycroft.sh
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: feature

#1545 Add SSML support for TTS
  mycroft/audio/speech.py
  mycroft/client/text/main.py
  mycroft/tts/__init__.py
  mycroft/tts/bing_tts.py
  mycroft/tts/espeak_tts.py
  mycroft/tts/fa_tts.py
  mycroft/tts/google_tts.py
  mycroft/tts/ibm_tts.py
  mycroft/tts/mary_tts.py
  mycroft/tts/mimic_tts.py
  mycroft/tts/remote_tts.py
  mycroft/tts/spdsay_tts.py
  test/unittests/tts/__init__.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes, type: feature

#1543 Fix websocket reconnect
  mycroft/messagebus/client/ws.py
Labels: CLA: Yes, type: bug

#1560 Add versioning to msm
  msm/msm
Labels: CLA: Yes, type: feature
