Repository MycroftAI/mycroft-core, pull requests merged in 2018-05, with the labels that each got.

#1568 The BIG move to python3
  .gitignore
  .travis.yml
  dev_setup.sh
  msm/msm
  mycroft/api/__init__.py
  mycroft/client/enclosure/__init__.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/client/text/main.py
  mycroft/configuration/config.py
  mycroft/messagebus/send.py
  mycroft/skills/audioservice.py
  mycroft/skills/core.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/intent_service.py
  mycroft/skills/main.py
  mycroft/skills/settings.py
  mycroft/tts/__init__.py
  mycroft/util/audio_test.py
  mycroft/util/lang/parse_fr.py
  mycroft/util/lang/parse_pt.py
  mycroft/util/parse.py
  start-mycroft.sh
  test/unittests/client/audio_consumer_test.py
  test/unittests/client/hotword_factory_test.py
  test/unittests/skills/core.py
  test/unittests/skills/intent_service.py
  test/unittests/skills/test_event_scheduler.py
  test/unittests/util/test_json_helper.py
  test/unittests/util/test_log.py
  test/unittests/util/test_parse.py
  test/unittests/util/test_parse_fr.py
  test/unittests/util/test_parse_it.py
  test/unittests/util/test_parse_pt.py
Labels: CLA: Yes

#1572 Cleanup skill loading and implement python msm
  msm/man/man1/msm.1
  msm/msm
  mycroft/configuration/mycroft.conf
  mycroft/skills/core.py
  mycroft/skills/main.py
  requirements.txt
  scripts/prepare-msm.sh
Labels: CLA: Yes

#1577 Add configuration values for msm
  mycroft/configuration/mycroft.conf
  mycroft/skills/main.py
Labels: CLA: Yes, type: feature

#1580 Make skill ids use skill folder
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/skills/main.py
  mycroft/skills/skill_data.py
  test/unittests/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1582 Fix trying to make integer from skill-id
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1585 Fix skill reloading when files in subdirectories change
  mycroft/skills/main.py
Labels: CLA: Yes, type: bug

#1589 Update msm version
  requirements.txt
Labels: CLA: Yes, MSM, type: bug

#1586 Make skill update interval configurable
  mycroft/configuration/mycroft.conf
  mycroft/skills/main.py
Labels: CLA: Yes, type: feature

#1590 Upgrade msm
  requirements.txt
Labels: CLA: Yes, type: feature

#1591 Stability improvements
  mycroft/skills/core.py
  mycroft/skills/main.py
Labels: CLA: Yes

#1593 Update msm
  requirements.txt
Labels: CLA: Yes

#1594 Make scp upload quiet and reduce saved seconds
  mycroft/client/speech/mic.py
Labels: CLA: Yes, type: bug

#1595 Log exception in skill settings and fix docstrings
  mycroft/skills/settings.py
Labels: CLA: Yes, type: bug

#1596 Update msm
  requirements.txt
Labels: CLA: Yes, type: feature

#1597 Upgrade msm
  requirements.txt
Labels: CLA: Yes, type: feature

#1599 Retry skill installation every 5 minutes if default skill install fails
  mycroft/skills/main.py
Labels: CLA: Yes, type: bug

#1600 Upgrade msm
  requirements.txt
Labels: CLA: Yes

#1607 Fix bad city information in test
  test/unittests/configuration/test_configuration.py
Labels: CLA: Yes, type: test

#1606 Re-add checking of dependencies when running start-mycroft.sh
  dev_setup.sh
  start-mycroft.sh
Labels: CLA: Yes, type: feature

#1563 keep message context
  mycroft/skills/core.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/main.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#1592 Remove all references to /opt/mycroft/skills
  mycroft/configuration/config.py
  mycroft/configuration/mycroft.conf
  mycroft/skills/event_scheduler.py
  mycroft/skills/main.py
  mycroft/tts/mimic_tts.py
  mycroft/util/__init__.py
  mycroft/version/__init__.py
  scripts/prepare-msm.sh
  test/integrationtests/skills/discover_tests.py
  test/unittests/api/test_api.py
Labels: CLA: Yes, Enhancement, Epic

#1608 Fix chromecast quitting app on mycroft shutdown.
  mycroft/audio/services/chromecast/__init__.py
Labels: CLA: Yes, type: bug
