Repository MycroftAI/mycroft-core, pull requests merged in 2018-06, with the labels that each got.

#1619 Feature/fix skill tester launch
  start-mycroft.sh
  test/integrationtests/skills/discover_tests.py
Labels: CLA: Yes, type: feature

#1621 Feature/padatious intent test
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#1623 Don't fail in dev_setup.sh if mimic fails to check version
  dev_setup.sh
Labels: CLA: Yes, type: bug

#1625 Add AdaptIntent alias
  mycroft/__init__.py
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
Labels: CLA: Yes, type: feature

#1626 Add msk
  requirements.txt
  skiller.sh
Labels: CLA: Yes, tagged for review and potential merge, type: feature

#1622 Fix missing attribute in error
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1613 Check that web cache exists before loading it
  mycroft/configuration/config.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1620 Make data optional in Message.reply()
  mycroft/messagebus/message.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1609 Use get_wch() to support unicode input
  mycroft/client/text/main.py
Labels: CLA: Yes, tagged for review and potential merge, type: feature

#1629 Change wake word upload to https request
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
  test/unittests/client/test_local_recognizer.py
Labels: CLA: Yes

#1628 Feature/pronounciations
  mycroft/res/text/en-us/phonetic_spellings.txt
  mycroft/tts/__init__.py
Labels: CLA: Yes

#1632 Upgrade msk to 0.3.9
  requirements.txt
Labels: type: feature

#1633 Add security notice running Mycroft from desktops
  start-mycroft.sh
Labels: CLA: Yes

#1615 Fixed dev_setup.sh for dnf users for python3 update
  dev_setup.sh
Labels: CLA: Yes, platform: fedora

#1634 German language support
  mycroft/res/text/de-de/cancel.voc
  mycroft/res/text/de-de/checking for updates.dialog
  mycroft/res/text/de-de/i didn't catch that.dialog
  mycroft/res/text/de-de/learning disabled.dialog
  mycroft/res/text/de-de/learning enabled.dialog
  mycroft/res/text/de-de/message_rebooting.dialog
  mycroft/res/text/de-de/message_synching.clock.dialog
  mycroft/res/text/de-de/message_updating.dialog
  mycroft/res/text/de-de/mycroft.intro.dialog
  mycroft/res/text/de-de/not connected to the internet.dialog
  mycroft/res/text/de-de/not.loaded.dialog
  mycroft/res/text/de-de/phonetic_spellings.txt
  mycroft/res/text/de-de/reset to factory defaults.dialog
  mycroft/res/text/de-de/skills updated.dialog
  mycroft/res/text/de-de/sorry I couldn't install default skills.dialog
  mycroft/res/text/de-de/ssh disabled.dialog
  mycroft/res/text/de-de/ssh enabled.dialog
  mycroft/skills/time_rules.py
  mycroft/util/format.py
  mycroft/util/lang/format_de.py
  mycroft/util/lang/parse_de.py
  mycroft/util/parse.py
  test/unittests/util/test_format_de.py
  test/unittests/util/test_parse_de.py
Labels: CLA: Yes, type: feature, type: translation

#1627 Fix changed default socket timeout
  mycroft/util/__init__.py
Labels: CLA: Yes, type: bug

#1636 Upgrade msm and padatious
  mycroft/skills/padatious_service.py
  requirements.txt
Labels: CLA: Yes, Enhancement

#1630 Make use of the default config when testing.
  test/unittests/api/test_api.py
  test/unittests/client/test_local_recognizer.py
  test/unittests/skills/test_core.py
  test/unittests/stt/test_stt.py
  test/util.py
Labels: CLA: Yes, type: test

#1637 Use time.monotonic instead of monotonic module
  mycroft/messagebus/client/ws.py
  mycroft/skills/main.py
  requirements.txt
Labels: CLA: Yes, type: Code Improvements / Refactor

#1641 Upgrade Padatious
  requirements.txt
Labels: CLA: Yes, type: feature

#1645 Moving wait_while_speaking to mycroft.audio.rst
  doc/source/mycroft.audio.rst
  doc/source/mycroft.util.rst
Labels: CLA: Yes, type: documentation

#1612 Feature/skill commands
  mycroft/client/text/main.py
  mycroft/skills/core.py
  mycroft/skills/main.py
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, tagged for review and potential merge, type: feature

#1635 Feature/nice date
  mycroft/res/text/da-dk/date_time.json
  mycroft/res/text/da-dk/date_time_test.json
  mycroft/res/text/en-au/date_time.json
  mycroft/res/text/en-au/date_time_test.json
  mycroft/res/text/en-us/date_time.json
  mycroft/res/text/en-us/date_time_test.json
  mycroft/util/format.py
  test/unittests/util/test_format.py
Labels: CLA: Yes, type: feature

#1651 fix extract date
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#1656 Feature add query mic status
  mycroft/client/speech/main.py
Labels: CLA: Yes, type: feature

#1654 govivace_stt
  mycroft/configuration/mycroft.conf
  mycroft/stt/__init__.py
Labels: CLA: Yes, type: feature

#1662 Upgrade Padaos
  requirements.txt
Labels: CLA: Yes
