Repository MycroftAI/mycroft-core, pull requests merged in 2018-09, with the labels that each got.

#1751 fix for broken communication with Arduino, added missing skill.error.dialog for language de-de
  mycroft/client/enclosure/__init__.py
  mycroft/res/text/de-de/skill.error.dialog
Labels: CLA: Yes

#1785 Make audiotest wait until playback is complete
  mycroft/util/audio_test.py
Labels: CLA: Yes

#1783 Bugfix/skill loading remnants
  mycroft/skills/core.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, type: bug

#1784 Unify the command line experience across platforms
  bin/mycroft-cli-client
  bin/mycroft-help
  bin/mycroft-mic-test
  bin/mycroft-msk
  bin/mycroft-msm
  bin/mycroft-pip
  bin/mycroft-say-to
  bin/mycroft-skill-testrunner
  bin/mycroft-speak
  dev_setup.sh
  start-mycroft.sh
  stop-mycroft.sh
  venv-activate.sh
Labels: CLA: Yes, status: in progress

#1788 Switch say/speak-to helper script names
  bin/mycroft-say-to
  bin/mycroft-speak
Labels: CLA: Yes, type: bug

#1791 Allow multiple dialogs and responses
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#1798 Update Arch (pacman) install for Python 3
  dev_setup.sh
Labels: CLA: Yes, platform: archlinux

#1799 Update packages for OpenSuse
  dev_setup.sh
Labels: CLA: Yes, platform: opensuse

#1804 Feature/extract datetime update
  mycroft/util/lang/parse_de.py
  mycroft/util/lang/parse_en.py
  mycroft/util/lang/parse_fr.py
  mycroft/util/lang/parse_it.py
  mycroft/util/lang/parse_pt.py
  mycroft/util/lang/parse_sv.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
  test/unittests/util/test_parse_de.py
  test/unittests/util/test_parse_fr.py
  test/unittests/util/test_parse_it.py
  test/unittests/util/test_parse_pt.py
  test/unittests/util/test_parse_sv.py
Labels: CLA: Yes

#1797 Fix incorrect escape sequences found by skill test
  mycroft/dialog/__init__.py
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes

#1571 added functions for the spanish parser
  mycroft/util/lang/parse_es.py
  mycroft/util/parse.py
Labels: CLA: Yes

#1806 Update gTTS-token module to fix google tts
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1805 Audioservice repeat
  mycroft/audio/audioservice.py
  mycroft/audio/services/__init__.py
  mycroft/audio/services/chromecast/__init__.py
  mycroft/audio/services/mopidy/__init__.py
  mycroft/audio/services/mplayer/__init__.py
  mycroft/audio/services/simple/__init__.py
  mycroft/audio/services/vlc/__init__.py
  mycroft/skills/audioservice.py
Labels: CLA: Yes, type: feature

#1789 Workaround for adapt issue with context + one_of
  mycroft/skills/intent_service.py
Labels: CLA: Yes, type: bug

#1808 Extract_datetime cleanup
  mycroft/util/lang/parse_de.py
  mycroft/util/lang/parse_en.py
  mycroft/util/lang/parse_it.py
  mycroft/util/lang/parse_sv.py
  mycroft/util/parse.py
Labels: CLA: Yes, tagged for review and potential merge

#1786 Test/test setup
  test/integrationtests/skills/discover_tests.py
  test/integrationtests/skills/runner.py
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#1800 Update requirements and pip install
  dev_setup.sh
  requirements.txt
  test-requirements.txt
Labels: CLA: Yes

#1816 Order results from translate_namedvalues()
  mycroft/skills/core.py
Labels: CLA: Yes, Enhancement

#1813 Add ability to schedule event in seconds
  mycroft/skills/core.py
Labels: CLA: Yes, Enhancement

#1812 Add "wait" option to MycroftSkill.speak() and speak_dialog()
  mycroft/skills/core.py
Labels: CLA: Yes, Enhancement

#1826 Fix Ctrl+C and Ctrl+X in CLI
  mycroft/client/text/__main__.py
  mycroft/client/text/text_client.py
Labels: CLA: Yes
