Repository MycroftAI/mycroft-core, pull requests merged in 2018-03, with the labels that each got.

#1456 Add proper not loaded message
  mycroft/client/speech/main.py
  mycroft/res/text/en-us/not.loaded.dialog
Labels: CLA: Yes, type: feature

#1455 Train Padatious on mycroft.skills.initialized
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, type: bug

#1452 Call callback when remote settings are inited
  mycroft/skills/settings.py
Labels: CLA: Yes, type: bug

#1459 Fix local service crash when servers are down
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/configuration/config.py
  mycroft/metrics/__init__.py
Labels: CLA: Yes, type: bug

#1458 Refactor handler argument calling
  mycroft/res/text/en-us/skill.error.dialog
  mycroft/skills/core.py
Labels: 18.02, CLA: Yes, type: Code Improvements / Refactor

#1461 Change git clone command in getting started to reduce clone size
  README.md
Labels: CLA: Needed

#1466 Reduce verbosity when skill settings fetch fails.
  mycroft/skills/settings.py
Labels: CLA: Yes

#1476 Fix accessing non-existent attribute in except blocks
  mycroft/client/speech/listener.py
  mycroft/configuration/config.py
Labels: CLA: Yes, type: bug

#1453 Msm update improvements
  msm/msm
Labels: 18.02, CLA: Yes, type: feature

#1498 Fix msm lock hanging forever
  msm/msm
Labels: CLA: Yes, type: bug

#1481 Feature/repeating event safety
  mycroft/skills/core.py
  mycroft/skills/event_scheduler.py
Labels: tagged for review and potential merge

#1500 Reduce audio service logging verbosity
  mycroft/audio/main.py
Labels: tagged for review and potential merge

#1355 Add support for installing on openSUSE
  dev_setup.sh
  scripts/prepare-msm.sh
Labels: CLA: Yes, platform: opensuse

#1507 Fix utterance_remainder for normalized keywords
  mycroft/messagebus/message.py
Labels: tagged for review and potential merge, type: bug

#1509 Wait for messagebus before emitting a message
  mycroft/client/enclosure/__init__.py
  mycroft/messagebus/client/ws.py
  test/integrationtests/messagebus/messagebus_test.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1463 Fix error on wait_for_response timeout.
  mycroft/messagebus/client/ws.py
Labels: CLA: Yes, type: bug

#1508 Add proper messages when the backend replies incorrectly
  mycroft/api/__init__.py
  mycroft/client/speech/listener.py
  mycroft/identity/__init__.py
  mycroft/res/text/en-us/backend.down.dialog
  mycroft/res/text/en-us/not connected to the internet.dialog
  mycroft/skills/main.py
Labels: CLA: Yes, type: feature

#1513 Fix msm not updating skills causing it to never finish booting up
  msm/msm
Labels: CLA: Yes, tagged for review and potential merge, type: bug
