Repository MycroftAI/mycroft-core, pull requests merged in 2018-02, with the labels that each got.

#1400 Add format and parsing methods for swedish
  mycroft/util/format.py
  mycroft/util/lang/format_sv.py
  mycroft/util/lang/parse_sv.py
  mycroft/util/parse.py
  test/unittests/util/test_parse_sv.py
Labels: CLA: Yes

#1364 Bugfix/scheduled event
  mycroft/skills/core.py
  test/unittests/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1423 wait_for_response method for synchronous messagebus communication
  mycroft/client/text/main.py
  mycroft/messagebus/client/ws.py
  mycroft/messagebus/message.py
Labels: CLA: Yes

#1359 Disable overflow exceptions when reading mic
  mycroft/client/speech/mic.py
Labels: CLA: Yes, platform: picroft

#1392 Skip skill update on startup if recent
  msm/msm
  mycroft/configuration/mycroft.conf
  mycroft/skills/main.py
Labels: CLA: Yes

#1406 Libfann Arch Linux
  dev_setup.sh
Labels: CLA: Yes

#1422 Make keywords per skill to fix overlapping keyword names
  mycroft/skills/core.py
  mycroft/skills/skill_data.py
  test/unittests/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1420 Reduce CLI log clutter from settings, etc
  mycroft/client/text/main.py
  mycroft/skills/settings.py
Labels: CLA: Yes, tagged for review and potential merge

#1421 Internal documentation, typos, remove misleading message
  mycroft/audio/main.py
  mycroft/client/enclosure/api.py
  mycroft/client/enclosure/display_manager.py
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/skills/main.py
Labels: CLA: Yes, tagged for review and potential merge

#1426 Add default when for schedule_repeating_event()
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1416 Issue-1375 - Fix and complete french translation
  mycroft/res/text/fr-fr/cancel.voc
  mycroft/res/text/fr-fr/checking for updates.dialog
  mycroft/res/text/fr-fr/i am awake.dialog
  mycroft/res/text/fr-fr/i didn't catch that.dialog
  mycroft/res/text/fr-fr/learning disabled.dialog
  mycroft/res/text/fr-fr/learning enabled.dialog
  mycroft/res/text/fr-fr/message_rebooting.dialog
  mycroft/res/text/fr-fr/message_synching.clock.dialog
  mycroft/res/text/fr-fr/message_updating.dialog
  mycroft/res/text/fr-fr/mycroft.intro.dialog
  mycroft/res/text/fr-fr/not connected to the internet.dialog
  mycroft/res/text/fr-fr/phonetic_spellings.txt
  mycroft/res/text/fr-fr/reset to factory defaults.dialog
  mycroft/res/text/fr-fr/skills updated.dialog
  mycroft/res/text/fr-fr/sorry I couldn't install default skills.dialog
  mycroft/res/text/fr-fr/time.changed.reboot.dialog
  mycroft/util/format.py
  mycroft/util/lang/format_common.py
  mycroft/util/lang/format_en.py
  mycroft/util/lang/format_fr.py
  mycroft/util/lang/format_it.py
  mycroft/util/lang/format_pt.py
  mycroft/util/lang/format_sv.py
  mycroft/util/lang/parse_fr.py
  mycroft/util/parse.py
  test/unittests/util/test_format_fr.py
  test/unittests/util/test_parse_fr.py
Labels: CLA: Yes

#1424 Add interface to Mark 1 faceplate capabilities
  mycroft/client/enclosure/api.py
  mycroft/client/enclosure/eyes.py
Labels: CLA: Yes, tagged for review and potential merge

#1427 Validate message before trying to demunge
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1425 Fix cancel_scheduled_event for non-repeating events by updateing pyee to v5.0.0
  mycroft/skills/core.py
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1263 Only emit start/stop messages for skill handlers by default (not all event handlers)
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#1428 Fix self parameter in decorator functions with single argument
  mycroft/skills/core.py
Labels: tagged for review and potential merge

#1429 Bugfix/msm register installed default skills
  msm/msm
Labels: CLA: Yes, MSM, tagged for review and potential merge

#1434 Bugfix/munging related issues
  mycroft/skills/core.py
  mycroft/skills/skill_data.py
  test/unittests/skills/core.py
Labels: CLA: Yes

#1436 issue #1083: limit history size to fix crash
  mycroft/client/text/main.py
Labels: CLA: Yes, Enhancement

#1438 Make sure the cli locale is set to an UTF-8 type
  mycroft/client/text/main.py
Labels: CLA: Yes

#1439 Improve docs within mycroft-conf
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#1441 Change precise executable to a folder
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes

#1447 Fix audio service loading
  mycroft/audio/main.py
Labels: CLA: Yes, type: bug

#1448 Fix platform comment in config
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#1446 Remove redundant except (SystemExit, KeyboardInterrupt) clauses
  mycroft/audio/main.py
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1449 Add message when skills are initialized
  mycroft/skills/main.py
Labels: CLA: Yes, type: feature

#1435 Fix multiple triggering of repeating events
  mycroft/skills/event_scheduler.py
Labels: CLA: Yes

#1450 Simplify version checking
  mycroft/version/__init__.py
  test/unittests/version/test_version.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1451 Check for pairing before performing routine polling
  mycroft/configuration/config.py
  mycroft/metrics/__init__.py
  mycroft/skills/settings.py
Labels: CLA: Yes, type: feature
