Repository MycroftAI/mycroft-core, pull requests merged in 2019-04, with the labels that each got.

#2090 Fix bug with paused audio
  mycroft/audio/services/simple/__init__.py
Labels: CLA: Yes

#2089 Remove "stop_threshold"
  mycroft/configuration/mycroft.conf
  test/unittests/util/commented.json
  test/unittests/util/plain.json
Labels: CLA: Yes, difficulty: easy

#2093 Fix infinitely adding pages to existing namespace
  mycroft/client/enclosure/base.py
Labels: CLA: Yes, GUI, type: bug

#2096 CommonIOT/acknowledge
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
  mycroft/res/snd/acknowledge.mp3
  mycroft/skills/common_iot_skill.py
  mycroft/skills/core.py
  mycroft/util/__init__.py
Labels: CLA: Yes

#2100 Restore get_response method after skill test is done
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug, type: test

#2094 Fix chown in dev_setup when GROUP != USER
  dev_setup.sh
Labels: CLA: Yes, tagged for review and potential merge

#2088 Feature/audioservice list
  mycroft/audio/audioservice.py
  mycroft/skills/audioservice.py
Labels: CLA: Yes, tagged for review and potential merge

#2095 Tidy up the readthedocs documentation
  doc/source/mycroft.rst
  mycroft/skills/common_play_skill.py
  mycroft/skills/common_query_skill.py
  start-mycroft.sh
Labels: CLA: Yes, type: documentation

#2070 Set default log level to INFO
  mycroft/util/__init__.py
  mycroft/util/log.py
Labels: CLA: Yes, tagged for review and potential merge

#2086 typo
  mycroft/res/text/de-de/date_time.json
Labels: CLA: Needed, CLA: Yes
