Repository MycroftAI/mycroft-core, pull requests merged in 2019-02, with the labels that each got.

#1978 Move sudo check to beginning of script
  dev_setup.sh
Labels: CLA: Yes, type: bug

#1984 update format_it.py test_format_it.py
  mycroft/util/lang/format_it.py
  test/unittests/util/test_format_it.py
Labels: CLA: Yes, tagged for review and potential merge

#1980 Document "save_utterance" option
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, tagged for review and potential merge

#1988 New formatters: nice_duration() and join_list()
  .gitignore
  mycroft/res/text/en-us/and.word
  mycroft/res/text/en-us/day.word
  mycroft/res/text/en-us/days.word
  mycroft/res/text/en-us/hour.word
  mycroft/res/text/en-us/hours.word
  mycroft/res/text/en-us/minute.word
  mycroft/res/text/en-us/minutes.word
  mycroft/res/text/en-us/or.word
  mycroft/res/text/en-us/second.word
  mycroft/res/text/en-us/seconds.word
  mycroft/util/format.py
  test/unittests/util/test_format.py
Labels: CLA: Yes, tagged for review and potential merge

#1977 Feature/issue 1959
  mycroft/util/lang/common_data_en.py
  mycroft/util/lang/format_en.py
  mycroft/util/lang/parse_en.py
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes, tagged for review and potential merge

#1991 Correcting a typo
  mycroft/api/__init__.py
Labels: CLA: Yes

#1985 Upgrade msm to 0.7.2
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1975 Update padatious and padaos
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#1992 Load .voc and .rx as utf-8
  mycroft/skills/settings.py
  mycroft/skills/skill_data.py
Labels: CLA: Yes

#1997 Add mattermost badge to README.md
  README.md
Labels: CLA: Yes

#1999 Add (|) syntax to dialog files
  mycroft/dialog/__init__.py
  mycroft/skills/skill_data.py
  mycroft/util/format.py
Labels: 19.02, CLA: Yes

#2000 Feature/remove old viseme system
  mycroft/enclosure/api.py
  mycroft/tts/__init__.py
  mycroft/tts/mimic2_tts.py
  mycroft/tts/mimic_tts.py
Labels: 19.02, CLA: Yes

#1995 Clean up some exception handling in settings code
  mycroft/messagebus/client/ws.py
  mycroft/skills/settings.py
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#2005 Support params for mycroft-mic-test
  bin/mycroft-mic-test
Labels: CLA: Yes

#2004 Tweak English extract_datetime() parsing
  mycroft/util/lang/parse_en.py
Labels: 19.02, CLA: Yes

#2010 Fix bug in the mic-level meter
  mycroft/client/text/text_client.py
Labels: CLA: Yes

#2011 Improve debug logging
  mycroft/client/text/text_client.py
  mycroft/util/__init__.py
Labels: CLA: Yes

#2009 Fix behavior of MycroftSkills.voc_match()
  mycroft/skills/core.py
  mycroft/skills/skill_data.py
  test/unittests/skills/locale/en-us/turn_off2_test.voc
  test/unittests/skills/locale/en-us/turn_off_test.voc
  test/unittests/skills/test_core.py
Labels: CLA: Yes

#2006 remove compaitbility methods for installer skill
  mycroft/skills/skill_manager.py
Labels: 19.02, CLA: Yes

#2014 Correct extract_duration doc and failure value
  mycroft/util/parse.py
Labels: CLA: Yes

#2016 Wait for ntp sync complete message
  mycroft/skills/__main__.py
Labels: 19.02, CLA: Yes, platform: mark1

#2017 Try updating the system on boot when not paired
  mycroft/skills/__main__.py
Labels: 19.02, CLA: Yes, platform: mark1

#2018 Add default values to Message attributes
  mycroft/messagebus/message.py
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
Labels: CLA: Yes

#1983 Issues-1982 - Add IAM authentication for Watson TTS
  mycroft/tts/ibm_tts.py
Labels: CLA: Yes

#2022 Upgrade msm to 0.7.3
  requirements.txt
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#1931 Use builtin cd for venv-activate.sh
  venv-activate.sh
Labels: CLA: Yes

#1998 Feature/update requirements
  mycroft/messagebus/client/ws.py
  mycroft/skills/settings.py
  requirements.txt
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2019 Refactor/19.02 removes
  mycroft/client/speech/listener.py
  mycroft/configuration/mycroft.conf
  mycroft/skills/core.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#1981 Feature/skill manager error checks
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2002 GUI Remove pages/namespaces
  mycroft/client/enclosure/base.py
  mycroft/skills/core.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2007 Let skill tester expand dialogs
  test/integrationtests/skills/skill_tester.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2023 date and time - for tonight, weekdays
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: 19.02, CLA: Yes

#2003 Update versions to 19.02
  mycroft/configuration/mycroft.conf
  mycroft/version/__init__.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2015 Feature/common io t
  .gitignore
  mycroft/skills/common_iot_skill.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge

#2024 Feature/threaded emitter for real
  mycroft/messagebus/client/threaded_event_emitter.py
  mycroft/messagebus/client/ws.py
  test/unittests/messagebus/__init__.py
  test/unittests/messagebus/client/__init__.py
  test/unittests/messagebus/client/test_threaded_event_emitter.py
Labels: 19.02, CLA: Yes

#2025 Deprecate self.config in skills
  mycroft/configuration/mycroft.conf
  mycroft/skills/core.py
  mycroft/skills/padatious_service.py
Labels: 19.02, CLA: Yes

#2027 More subtle "listening" sound
  mycroft/res/snd/start_listening.wav
Labels: 19.02, CLA: Yes

#2026 Tweak CommonPlay scoring
  mycroft/skills/common_play_skill.py
Labels: 19.02, CLA: Yes

#2029 Typo in Common Query 'encolsure'
  mycroft/skills/common_query_skill.py
Labels: 19.02, CLA: Yes

#2030 Hide deprecated warning in certain cases
  mycroft/skills/core.py
Labels: 19.02, CLA: Yes

#2031 Improve user feedback during startup
  mycroft/res/text/en-us/message_loading.skills.dialog
  mycroft/skills/__main__.py
  mycroft/skills/padatious_service.py
  mycroft/skills/skill_manager.py
Labels: 19.02, CLA: Yes, tagged for review and potential merge
