Repository MycroftAI/mycroft-core, pull requests merged in 2019-03, with the labels that each got.

#2034 Initial spanish format functions
  mycroft/util/format.py
  mycroft/util/lang/common_data_es.py
  mycroft/util/lang/format_es.py
  test/unittests/util/test_format.py
  test/unittests/util/test_format_es.py
Labels: CLA: Yes

#2035 Ignore the 'skills' symlink
  .gitignore
Labels: CLA: Yes

#2036 Give Padatious high and low match passes
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, tagged for review and potential merge

#2041 Set a default locale when running dev_setup.sh
  dev_setup.sh
Labels: CLA: Yes

#2042 Mute the mic while playing the listening "beep"
  mycroft/client/speech/mic.py
Labels: CLA: Yes

#2043 Bugfix for Mimic2 issues
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#2044 Add pause/resume to simple audio services
  mycroft/audio/services/simple/__init__.py
Labels: CLA: Yes

#2045 Fix simple audio backend pausing by voice
  mycroft/audio/services/simple/__init__.py
Labels: CLA: Yes

#2040 Fix context handling in skill tester
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#2049 Remove skills directory link.
  skills
Labels: CLA: Yes

#2046 Fix dialog check in skill tester
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, type: test

#2050 Feature/common io t updates
  mycroft/skills/common_iot_skill.py
Labels: CLA: Yes, tagged for review and potential merge

#2053 Change default lang to None, not English
  mycroft/skills/__main__.py
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/util/format.py
  mycroft/util/lang/__init__.py
  mycroft/util/lang/parse_it.py
  mycroft/util/lang/parse_pt.py
  mycroft/util/parse.py
  test/unittests/util/test_format_de.py
  test/unittests/util/test_parse.py
  test/unittests/util/test_parse_fr.py
  test/unittests/util/test_parse_pt.py
Labels: CLA: Yes, tagged for review and potential merge, type: translation

#2012 Protect against failure to launch WAV/MP3
  mycroft/util/__init__.py
Labels: CLA: Yes, tagged for review and potential merge

#2058 Feature/non hard coded paths
  mycroft/configuration/config.py
  mycroft/configuration/locations.py
  mycroft/util/signal.py
Labels: CLA: Yes

#2059 Adjust and document Padatious loose fallback priority
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, tagged for review and potential merge

#2061 Fix mimic 2 long sentences
  mycroft/tts/__init__.py
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#2060 Make precise sensitivity configurable
  mycroft/client/speech/hotword_factory.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#2063 Remove enum.auto
  mycroft/skills/common_iot_skill.py
Labels: CLA: Yes

#2039 feature/format_pt
  mycroft/util/format.py
  mycroft/util/lang/common_data_pt.py
  mycroft/util/lang/format_pt.py
  mycroft/util/lang/parse_pt.py
  test/unittests/util/test_format_pt.py
Labels: CLA: Yes

#2057 Add the SkillGUI method send_event()
  mycroft/client/enclosure/base.py
  mycroft/skills/core.py
Labels: CLA: Yes, GUI, tagged for review and potential merge

#1994 Install pep8 check as pre-commit hook
  dev_setup.sh
  scripts/pre-commit
Labels: CLA: Yes, tagged for review and potential merge

#2066 handling tonight in date & time extraction
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#2069 Update gTTS to 2.0.3
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#2071 separate the cache & avoid voice overlap
  mycroft/audio/speech.py
  mycroft/tts/__init__.py
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes, tagged for review and potential merge

#2067 Normalize utterances before intent handling
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, tagged to merge after release

#2073 Adapt: Run normalized also when raw matches None
  mycroft/skills/intent_service.py
Labels: CLA: Yes, tagged for review and potential merge
