Repository MycroftAI/mycroft-core, pull requests merged in 2019-07, with the labels that each got.

#2178 Feature/docs format parse
  doc/source/mycroft.rst
  doc/source/mycroft.util.format.rst
  doc/source/mycroft.util.parse.rst
  doc/source/mycroft.util.rst
  doc/source/mycroft.util.time.rst
  mycroft/skills/core.py
  mycroft/util/format.py
  mycroft/util/parse.py
Labels: CLA: Yes

#2172 Correct skill GID's for skills not in the marketplace
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#2177 Remove incorrect settings meta upload disable flag
  mycroft/skills/settings.py
Labels: CLA: Yes, tagged for review and potential merge

#2182 Remove 'update' field from skills data
  mycroft/api/__init__.py
Labels: CLA: Yes

#2183 Feature/better listener update
  mycroft/client/speech/listener.py
  test/unittests/client/test_local_recognizer.py
Labels: CLA: Yes

#2185 Resting screen handler name fix
  mycroft/skills/core.py
  test/unittests/skills/test_core.py
Labels: CLA: Yes

#2187 Fix parsing dates in utterances that include non-month 'may'
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#2196 Add skill_id to skill handler timing report
  mycroft/skills/core.py
Labels: CLA: Yes

#2198 Only report STT timing if transcription exists
  mycroft/client/speech/listener.py
Labels: CLA: Yes

#2197 Skills process startup speedup
  mycroft/skills/__main__.py
  mycroft/skills/settings.py
  mycroft/skills/skill_manager.py
  requirements.txt
Labels: CLA: Yes

#2201 Explain the config system used for the log level.
  doc/source/mycroft.rst
  doc/source/mycroft.util.log.rst
  mycroft/configuration/mycroft.conf
  mycroft/util/log.py
Labels: CLA: Yes

#2192 Fetch CLI log path from config if available
  mycroft/client/text/__main__.py
Labels: CLA: Yes

#2190 Recognize "confirm[ed]" as a word for "yes"
  mycroft/res/text/en-us/yes.voc
Labels: CLA: Yes

#2203 Add mycroft_mark_2pi to platforms needing ntp sync
  mycroft/skills/__main__.py
Labels: CLA: Yes

#2184 'next {day}' to be 3-9 days in future
  mycroft/util/lang/parse_en.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#2211 Trigger settings update on pairing complete
  mycroft/skills/core.py
Labels: CLA: Yes

#2206 Quickfix: readthedocs build
  mycroft/skills/settings.py
Labels: CLA: Yes

#2213 Refactor message bus
  mycroft/audio/__main__.py
  mycroft/client/enclosure/__main__.py
  mycroft/client/enclosure/base.py
  mycroft/client/speech/__main__.py
  mycroft/client/text/gui_server.py
  mycroft/client/text/text_client.py
  mycroft/enclosure/display_manager.py
  mycroft/messagebus/client/__init__.py
  mycroft/messagebus/client/client.py
  mycroft/messagebus/client/ws.py
  mycroft/messagebus/load_config.py
  mycroft/messagebus/message.py
  mycroft/messagebus/send.py
  mycroft/messagebus/service/__main__.py
  mycroft/messagebus/service/event_handler.py
  mycroft/skills/__main__.py
  mycroft/util/__init__.py
  test/integrationtests/messagebus/messagebus_test.py
Labels: CLA: Yes, tagged for review and potential merge, type: Code Improvements / Refactor

#2216 Check for terminals ability to display colours
  dev_setup.sh
Labels: CLA: Yes, tagged for review and potential merge

#2217 Move quick skill update to after internet check
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, tagged for review and potential merge

#2218 Update msm to v0.7.9
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#2228 tts_hash to an actual hash
  mycroft/audio/speech.py
Labels: CLA: Yes

#2230 Bugfix/message bus build url
  mycroft/messagebus/client/client.py
  test/unittests/messagebus/client/test_client.py
Labels: CLA: Yes

#2231 Limit creation attempts of msm-lock
  mycroft/skills/msm_wrapper.py
Labels: CLA: Yes

#2220 Refactor skill service
  mycroft/audio/__main__.py
  mycroft/audio/speech.py
  mycroft/client/enclosure/base.py
  mycroft/client/speech/__main__.py
  mycroft/client/text/text_client.py
  mycroft/configuration/config.py
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#2221 Split mycroft.skills.core
  mycroft/__init__.py
  mycroft/enclosure/gui.py
  mycroft/skills/__init__.py
  mycroft/skills/common_iot_skill.py
  mycroft/skills/common_play_skill.py
  mycroft/skills/common_query_skill.py
  mycroft/skills/core.py
  mycroft/skills/fallback_skill.py
  mycroft/skills/mycroft_skill.py
Labels: CLA: Yes, tagged to merge after release, type: Code Improvements / Refactor

#2233 Small cleanup of the event scheduler
  mycroft/skills/event_scheduler.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#2180 Make is_paired fail early if no uuid in identity
  mycroft/api/__init__.py
  test/unittests/api/test_api.py
Labels: CLA: Yes, tagged for review and potential merge

#2235 Handle removing unregistered intents
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, type: test
