Repository MycroftAI/mycroft-core, pull requests merged in 2019-05, with the labels that each got.

#2109 Add support for values
  mycroft/skills/common_iot_skill.py
Labels: CLA: Yes

#2116 Add delay on failure to upload skillsettingsmeta
  mycroft/skills/settings.py
Labels: CLA: Yes

#2119 Fix typo in mycroft.conf
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, type: documentation

#2111 Speak sayto bash pipes
  bin/mycroft-say-to
  bin/mycroft-speak
Labels: CLA: Yes

#2113 Allow settingsmeta to be a yaml file
  mycroft/skills/settings.py
  requirements.txt
Labels: CLA: Yes, type: feature

#2106 feature/enable sending qml ui over network
  mycroft/skills/core.py
Labels: CLA: Yes, platform: mark2, status: waiting for fix, type: feature

#2115 Feature/pre_loaded_cache
  mycroft/configuration/mycroft.conf
  mycroft/tts/cache_handler.py
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes

#2097 Feature/common qa skill test
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, tagged for review and potential merge, type: test

#2125 Feature/pycodestyle
  .travis.yml
  dev_setup.sh
  mycroft/api/__init__.py
  mycroft/audio/services/mopidy/__init__.py
  mycroft/audio/services/mopidy/mopidypost.py
  mycroft/messagebus/service/ws.py
  mycroft/stt/__init__.py
  mycroft/tts/__init__.py
  mycroft/tts/espeak_tts.py
  mycroft/tts/fa_tts.py
  mycroft/tts/google_tts.py
  mycroft/tts/mary_tts.py
  mycroft/tts/mimic_tts.py
  mycroft/tts/spdsay_tts.py
  scripts/pre-commit
  test-requirements.txt
  test/unittests/tts/test_tts.py
  test/unittests/util/test_format_it.py
Labels: CLA: Yes, type: bug

#2121 Feature/System_QML
  mycroft/res/ui/SYSTEM_ImageFrame.qml
  mycroft/res/ui/SYSTEM_TextFrame.qml
  mycroft/skills/core.py
Labels: CLA: Yes, GUI, status: in progress

#2124 Support chopping old audio via precise upgrade
  mycroft/client/speech/hotword_factory.py
  requirements.txt
Labels: CLA: Yes, type: feature

#2126 Remove additional space after initials
  mycroft/audio/speech.py
Labels: CLA: Yes

#2104 Feature/skill gid
  .travis.yml
  mycroft/api/__init__.py
  mycroft/skills/msm_wrapper.py
  mycroft/skills/settings.py
  mycroft/skills/skill_manager.py
  requirements.txt
  test/unittests/skills/test_settings.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/util/test_signal.py
Labels: CLA: Yes, status: in progress, tagged to merge after release

#2130 Fix copy/paste error in chmod command
  scripts/mycroft-use.sh
Labels: CLA: Yes

#2134 Pass the device id as part of the refresh sequence
  mycroft/api/__init__.py
Labels: CLA: Yes

#2132 Don't create skill settings for Padatious Service
  mycroft/skills/core.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, type: bug

#2136 Feature/msm 0.7.6
  mycroft/skills/__main__.py
  requirements.txt
Labels: CLA: Yes, type: bug

#2133 Use SafeLoader to load settingsmeta yaml
  mycroft/skills/settings.py
Labels: CLA: Yes

#2114 GUI updates
  mycroft/client/enclosure/base.py
  mycroft/skills/core.py
Labels: CLA: Yes, GUI, tagged for review and potential merge, type: bug, type: feature

#2138 Add System QML support for HTML displays
  mycroft/res/ui/SYSTEM_HtmlFrame.qml
  mycroft/res/ui/SYSTEM_UrlFrame.qml
  mycroft/res/ui/WebViewHtmlFrame.qml
  mycroft/res/ui/WebViewUrlFrame.qml
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge

#2141 Restored ability to store wakewords locally
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, tagged for review and potential merge
