Repository MycroftAI/mycroft-core, pull requests merged in 2019-01, with the labels that each got.

#1927 Bugfix/mimic2 negative numbers
  mycroft/tts/mimic2_tts.py
  mycroft/util/lang/format_en.py
  test/unittests/util/test_format.py
Labels: CLA: Yes, type: bug

#1930 dev_setup: Exit if pip installation fails.
  dev_setup.sh
Labels: CLA: Yes

#1936 Support selecting microphone by name
  mycroft/client/speech/listener.py
  mycroft/configuration/mycroft.conf
  mycroft/util/__init__.py
Labels: CLA: Yes

#1939 GUI Cleanup
  mycroft/client/enclosure/base.py
  mycroft/client/text/gui_server.py
Labels: CLA: Yes

#1945 Remove inheritance from object
  mycroft/api/__init__.py
  mycroft/audio-accuracy-test/audio_accuracy_test.py
  mycroft/audio/audioservice.py
  mycroft/audio/services/__init__.py
  mycroft/audio/services/mopidy/mopidypost.py
  mycroft/client/enclosure/base.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/configuration/config.py
  mycroft/dialog/__init__.py
  mycroft/enclosure/display_manager.py
  mycroft/filesystem/__init__.py
  mycroft/identity/__init__.py
  mycroft/lock/__init__.py
  mycroft/messagebus/client/ws.py
  mycroft/messagebus/message.py
  mycroft/metrics/__init__.py
  mycroft/session/__init__.py
  mycroft/skills/audioservice.py
  mycroft/skills/core.py
  mycroft/skills/intent_service.py
  mycroft/stt/__init__.py
  mycroft/tts/__init__.py
  mycroft/util/combo_lock.py
  mycroft/version/__init__.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#1948 Remove depth=1, which breaks the dev_setup wizard
  README.md
Labels: CLA: Yes, type: bug, type: documentation

#1912 italian translation minor update
  mycroft/res/text/it-it/date_time.json
  mycroft/res/text/it-it/date_time_test.json
  mycroft/util/format.py
  mycroft/util/lang/format_it.py
  mycroft/util/lang/parse_it.py
  test/unittests/util/test_format_it.py
  test/unittests/util/test_parse_it.py
Labels: CLA: Yes

#1944 feature/audio seek
  mycroft/audio/audioservice.py
  mycroft/audio/services/__init__.py
  mycroft/audio/services/vlc/__init__.py
  mycroft/skills/audioservice.py
Labels: CLA: Yes, tagged for review and potential merge, type: feature

#1928 patch for issue #1868
  mycroft/skills/core.py
Labels: CLA: Yes, Enhancement

#1906 Dev add nl nl
  mycroft/res/text/nl-nl/backend.down.dialog
  mycroft/res/text/nl-nl/cancel.voc
  mycroft/res/text/nl-nl/checking for updates.dialog
  mycroft/res/text/nl-nl/date_time.json
  mycroft/res/text/nl-nl/date_time_test.json
  mycroft/res/text/nl-nl/message_rebooting.dialog
  mycroft/res/text/nl-nl/message_synching.clock.dialog
  mycroft/res/text/nl-nl/message_updating.dialog
  mycroft/res/text/nl-nl/mycroft.intro.dialog
  mycroft/res/text/nl-nl/no.voc
  mycroft/res/text/nl-nl/not.loaded.dialog
  mycroft/res/text/nl-nl/phonetic_spellings.txt
  mycroft/res/text/nl-nl/skill.error.dialog
  mycroft/res/text/nl-nl/time.changed.reboot.dialog
  mycroft/res/text/nl-nl/yes.voc
  mycroft/util/format.py
  mycroft/util/lang/format_nl.py
  start-mycroft.sh
  test/unittests/util/test_format_nl.py
Labels: CLA: Yes, type: translation

#1889 Run emitter using threadpool
  mycroft/messagebus/client/threaded_event_emitter.py
  mycroft/messagebus/client/ws.py
  requirements.txt
  test/unittests/messagebus/__init__.py
  test/unittests/messagebus/client/__init__.py
  test/unittests/messagebus/client/test_threaded_event_emitter.py
Labels: CLA: Yes

#1954 Fix Ctrl+C handling in CLI
  mycroft/client/text/text_client.py
Labels: CLA: Yes

#1957 text_client.py: Don't throw exception on missing conf
  mycroft/client/text/text_client.py
Labels: CLA: Yes

#1964 GUI update number 6
  mycroft/client/enclosure/base.py
  mycroft/skills/core.py
Labels: CLA: Yes, type: feature

#1969 Allow running mycroft on embedded devices without sudo
  dev_setup.sh
  scripts/prepare-msm.sh
Labels: CLA: Yes

#1974 Fix registering fallback
  mycroft/skills/core.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1973 Single viseme message
  mycroft/client/enclosure/mark1/mouth.py
  mycroft/enclosure/api.py
  mycroft/tts/__init__.py
Labels: CLA: Yes, platform: mark1, platform: mark2

#1961 Bugfix/speech stop
  mycroft/audio/speech.py
  mycroft/tts/__init__.py
  mycroft/tts/mimic2_tts.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#1971 Add some additional info to audiotest
  mycroft/util/audio_test.py
Labels: CLA: Yes

#1925 CLI: Use language set in mycroft configuration
  mycroft/client/text/__main__.py
  mycroft/client/text/text_client.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug, type: translation

#1952 Add python version option to dev_setup.sh
  dev_setup.sh
Labels: CLA: Yes

#1963 Play on local audiobackends before trying remotes
  mycroft/audio/audioservice.py
  mycroft/audio/services/__init__.py
  mycroft/audio/services/chromecast/__init__.py
  mycroft/audio/services/mopidy/__init__.py
Labels: CLA: Yes, tagged for review and potential merge, type: feature

#1853 Add tests for commented dialogs and DialogLoader
  mycroft/dialog/__init__.py
  test/unittests/dialog/multiple_dialogs/one.dialog
  test/unittests/dialog/multiple_dialogs/two.dialog
  test/unittests/dialog/mustache_templates_comments/example-comments.dialog
  test/unittests/dialog/mustache_templates_comments/example-comments.result
  test/unittests/dialog/test_dialog.py
Labels: CLA: Yes, tagged for review and potential merge, type: test
