Repository MycroftAI/mycroft-core, pull requests merged in 2019-06, with the labels that each got.

#2145 Fix usage of mtd before assignment
  mycroft/client/speech/mic.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#2140 Skill settings cleanup
  mycroft/api/__init__.py
  mycroft/skills/settings.py
Labels: CLA: Yes, tagged for review and potential merge

#2156 Remove abstractmethod for MycroftSkill.stop()
  mycroft/skills/core.py
Labels: CLA: Yes

#2149 Feature/streamingstt
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/stt/__init__.py
  test/unittests/client/test_audio_consumer.py
Labels: CLA: Yes

#2157 Remove unused subprocess module
  mycroft/audio/services/simple/__init__.py
Labels: CLA: Yes

#2158 Add mycroft.util.time.to_system()
  mycroft/util/time.py
Labels: CLA: Yes

#2152 Skill manifest upload checks
  mycroft/api/__init__.py
  test/unittests/api/test_api.py
Labels: CLA: Yes

#2160 Feature: Google Streaming STT
  mycroft/stt/__init__.py
Labels: CLA: Yes

#2163 Bugfix/metaclass
  mycroft/audio/services/__init__.py
  mycroft/stt/__init__.py
  mycroft/tts/__init__.py
Labels: CLA: Yes

#2162 Limit travis branch builds to dev and master
  .travis.yml
Labels: CLA: Yes

#2150 CommonIoT/state
  mycroft/skills/common_iot_skill.py
Labels: CLA: Yes

#2170 Add gui related messages to list of hidden messages
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes

#2151 Make sure CLI help section shows everything
  mycroft/client/text/text_client.py
Labels: CLA: Yes

#2165 Feature/better os detection
  dev_setup.sh
Labels: CLA: Yes

#2169 Allow setting loglevel for speech / voice service
  mycroft/client/speech/__main__.py
Labels: CLA: Yes

#2166 Update dev_setup.sh to use and benefit from bash double square bracket syntax
  dev_setup.sh
Labels: CLA: Yes

#2167 [Debian] Replace Python 2 packages by their Python 3 counterparts and remove doubled "automake"
  dev_setup.sh
Labels: CLA: Yes

#2168 Update pychromecast to 3.2.2
  mycroft/audio/services/chromecast/__init__.py
  requirements.txt
Labels: CLA: Yes

#2171 Read .voc files as lowercase
  mycroft/client/speech/listener.py
  mycroft/skills/skill_data.py
Labels: CLA: Yes, tagged for review and potential merge

#2173 Fix debian detection
  dev_setup.sh
Labels: CLA: Yes

#2174 German spelling: May => Mai
  mycroft/res/text/de-de/date_time.json
Labels: CLA: Yes

#2176 Lock cryptography version to 2.6.1
  requirements.txt
Labels: CLA: Yes
