Repository MycroftAI/mycroft-core, pull requests merged in 2019-08, with the labels that each got.

#2209 support ubuntu & mint (debian like) OS
  dev_setup.sh
Labels: CLA: Yes

#2234 Some swedish additions
  mycroft/res/text/sv-se/date_time.json
  mycroft/res/text/sv-se/date_time_test.json
  mycroft/util/format.py
  mycroft/util/lang/format_sv.py
  test/unittests/util/test_format_sv.py
Labels: CLA: Yes, type: translation

#2241 Undefined name: Except --> Exception
  mycroft/tts/google_tts.py
Labels: CLA: Yes

#2242 Use ==/!= to compare str, bytes, and int literals
  mycroft/util/lang/parse_en.py
Labels: CLA: Yes

#2254 Bugfix/delete settings meta
  mycroft/api/__init__.py
  test/unittests/api/test_api.py
Labels: CLA: Yes, type: bug

#2236 Allow startup if update attempt occurs
  mycroft/skills/__main__.py
Labels: CLA: Yes, type: bug

#2248 Move pairing check to the relevant stt backends
  mycroft/client/speech/listener.py
  mycroft/stt/__init__.py
Labels: CLA: Yes

#2258 Fix TypeError for number values in settings
  mycroft/skills/settings.py
Labels: CLA: Yes

#2237 Refactor skill manager
  mycroft/messagebus/__init__.py
  mycroft/skills/__main__.py
  mycroft/skills/core.py
  mycroft/skills/skill_loader.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  test/integrationtests/skills/skill_tester.py
  test/unittests/base.py
  test/unittests/mocks.py
  test/unittests/skills/test_core.py
  test/unittests/skills/test_skill_loader.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/skills/test_skill_updater.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#2245 Bugfix/download precise
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/listener.py
Labels: CLA: Yes

#2260 Fix issue where skills fail during initialize()
  mycroft/skills/skill_loader.py
Labels: CLA: Yes

#2266 Bugfix/ prevent uninstall of WINE and other programs
  dev_setup.sh
Labels: CLA: Yes, platform: debian, type: bug

#2267 Feature/better no confirm listening
  mycroft/client/speech/mic.py
Labels: CLA: Yes

#2263 Fix reload_allowed check
  mycroft/skills/skill_loader.py
  test/unittests/skills/test_skill_loader.py
Labels: CLA: Yes

#2257 Allow dnf to be used as pkg manager for Fedora #2255
  dev_setup.sh
Labels: CLA: Yes

#2268 if libjack package conflict detected - require user to review package changes
  dev_setup.sh
Labels: CLA: Yes

#2265 Changes to MSM logic to improve performance.
  mycroft/skills/msm_wrapper.py
  mycroft/skills/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
  requirements.txt
  test/unittests/base.py
  test/unittests/mocks.py
  test/unittests/skills/test_skill_loader.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/skills/test_skill_updater.py
Labels: CLA: Yes

#2271 Fix stacktrace on use of deprecated config member
  mycroft/skills/mycroft_skill.py
Labels: CLA: Yes

#2273 Send recording message after playing recording sound
  mycroft/client/speech/mic.py
Labels: CLA: Yes

#2274 Switch all mock imports to unittest.mock imports
  test-requirements.txt
  test/unittests/api/test_api.py
  test/unittests/client/test_local_recognizer.py
  test/unittests/configuration/test_configuration.py
  test/unittests/lock/test_lock.py
  test/unittests/messagebus/client/test_client.py
  test/unittests/skills/test_core.py
  test/unittests/skills/test_event_scheduler.py
  test/unittests/skills/test_settings.py
  test/unittests/stt/test_stt.py
  test/unittests/version/test_version.py
Labels: CLA: Yes

#2275 Force install if IS_TRAVIS
  dev_setup.sh
Labels: CLA: Yes

#2277 Feature/log merger
  mycroft/client/text/text_client.py
  mycroft/util/log.py
  scripts/log_merger.py
Labels: CLA: Yes

#2278 Switch msm branch to 19.08
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#2279 Fix typo when unreferencing skill after failed load
  mycroft/skills/skill_loader.py
Labels: CLA: Yes

#2256 Refactor MycroftSkill
  mycroft/skills/event_scheduler.py
  mycroft/skills/intent_service.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/mycroft_skill/__init__.py
  mycroft/skills/mycroft_skill/decorators.py
  mycroft/skills/mycroft_skill/event_container.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_data.py
  mycroft/skills/skill_loader.py
  test/unittests/skills/test_event_container.py
  test/unittests/skills/test_intent_service_interface.py
  test/unittests/skills/test_mycroft_skill.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#2281 fix MycroftSkill registered_intents instance attribute
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_mycroft_skill.py
Labels: CLA: Yes
