Repository MycroftAI/mycroft-core, pull requests merged in 2020-02, with the labels that each got.

#2467 Make audio accuracy test runnable again
  .gitignore
  start-mycroft.sh
  test/wake_word/README.md
  test/wake_word/__main__.py
  test/wake_word/wake_word_test.py
Labels: CLA: Yes, type: test

#2460 Added a cl tool to start mycroft to listen: mycroft-listen
  bin/mycroft-listen
Labels: CLA: Yes, tagged for review and potential merge

#2422 Refactor mycroft.dialog
  mycroft/dialog/__init__.py
  mycroft/dialog/dialog.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: CLA: Yes, tagged for review and potential merge, type: Code Improvements / Refactor

#2459 Common play skill tests
  mycroft/skills/audioservice.py
  mycroft/skills/common_play_skill.py
  test/unittests/skills/test_audioservice.py
  test/unittests/skills/test_common_play_skill.py
Labels: CLA: Yes, tagged for review and potential merge, type: test

#2462 Tests for CommonQuerySkill
  mycroft/skills/common_query_skill.py
  test/unittests/skills/test_common_query_skill.py
Labels: CLA: Yes, tagged for review and potential merge, type: test

#2469 Remove backwards compat. imports from lang tools
  mycroft/util/format.py
  mycroft/util/lang.py
  mycroft/util/lang/__init__.py
  mycroft/util/lang/format_common.py
  mycroft/util/lang/format_da.py
  mycroft/util/lang/format_de.py
  mycroft/util/lang/format_en.py
  mycroft/util/lang/format_es.py
  mycroft/util/lang/format_hu.py
  mycroft/util/lang/format_it.py
  mycroft/util/lang/format_nl.py
  mycroft/util/lang/format_pt.py
  mycroft/util/lang/format_sv.py
  mycroft/util/lang/parse_common.py
  mycroft/util/lang/parse_da.py
  mycroft/util/lang/parse_de.py
  mycroft/util/lang/parse_en.py
  mycroft/util/lang/parse_es.py
  mycroft/util/lang/parse_fr.py
  mycroft/util/lang/parse_it.py
  mycroft/util/lang/parse_nl.py
  mycroft/util/lang/parse_pt.py
  mycroft/util/lang/parse_sv.py
  mycroft/util/parse.py
  test/unittests/util/test_format.py
  test/unittests/util/test_parse.py
Labels: 20.02, CLA: Yes, type: Code Improvements / Refactor

#2470 Remove the ConfigurationManager compatibility
  mycroft/configuration/__init__.py
Labels: 20.02, CLA: Yes, type: Code Improvements / Refactor

#2461 Feat/message targetting
  mycroft/audio/speech.py
  mycroft/client/speech/__main__.py
  mycroft/client/text/text_client.py
  mycroft/enclosure/api.py
  mycroft/messagebus/message.py
  mycroft/skills/common_iot_skill.py
  mycroft/skills/common_play_skill.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/fallback_skill.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_event_scheduler.py
Labels: 20.02, CLA: Yes, Enhancement

#2473 Fallback to mimic for bad http status codes
  mycroft/audio/speech.py
  mycroft/tts/mimic2_tts.py
  mycroft/tts/remote_tts.py
  test/unittests/audio/test_speech.py
  test/unittests/tts/test_mimic2_tts.py
Labels: CLA: Yes

#2474 msm default to 20.02
  mycroft/configuration/mycroft.conf
  requirements.txt
Labels: CLA: Yes

#2476 Bugfix for padatious and converse responses
  mycroft/messagebus/message.py
  mycroft/skills/intent_service.py
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#2468 intent api
  mycroft/skills/intent_service.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/padatious_service.py
Labels: 20.02, CLA: Yes, Enhancement

#2478 Make message.response keep source/dest info
  mycroft/messagebus/message.py
Labels: CLA: Yes

#2472 Convert hash sign comments to double slash (# -> //)
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#2481 Feature/timing out of thread
  mycroft/metrics/__init__.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#2482 remove deprecated Settings class
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  test/integrationtests/skills/skill_tester.py
  test/unittests/skills/test_settings.py
  test/unittests/skills/test_skill_loader.py
Labels: CLA: Yes

#2483 Bump the version to the new 20.02 range
  mycroft/version/__init__.py
Labels: CLA: Yes

#2477 Added a "save_path" configuration for saved wake words and utterances.
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#2485 Remove debug logging of stop message context
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: CLA: Yes
