Repository MycroftAI/mycroft-core, pull requests merged in 2020-11, with the labels that each got.

#2746 Enable utf-8 encoding during dev-setup.sh
  dev_setup.sh
Labels: CLA: Yes, Type: Bug - quick

#2745 Only build mimic once during travis tests
  .travis.yml
Labels: CLA: Yes, Type: Tests

#2748 Fix typo preventing STT plugins to load
  mycroft/stt/__init__.py
Labels: CLA: Yes

#2742 Fix Voight kampff reset of patched config
  test/integrationtests/voight_kampff/features/environment.py
  test/integrationtests/voight_kampff/features/steps/configuration.py
Labels: CLA: Yes, Type: Tests

#2749 Fix readthedocs build
  .readthedocs.yml
  doc/conf.py
  mycroft/skills/settings.py
Labels: CLA: Yes, Type: Bug - quick

#2666 cps extend timeout
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - proposed

#2759 Run CLA check on all branches
  Jenkinsfile
Labels: CLA: Yes

#2718 Handle Mimic missing properly
  mycroft/audio/speech.py
  mycroft/tts/mimic_tts.py
Labels: CLA: Yes, Type: Bug - quick

#2763 Update gTTS to version 2.2.0
  requirements/requirements.txt
Labels: CLA: Yes
