Repository MycroftAI/mycroft-core, pull requests merged in 2020-01, with the labels that each got.

#2440 The command to run unittests was wrong documented
  .github/CONTRIBUTING.md
Labels: CLA: Yes

#2439 Make venv-activate.sh compatible with sh and zsh
  venv-activate.sh
Labels: CLA: Yes

#2446 Add self.root_dir to readthedocs documentation
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: CLA: Yes, type: documentation

#2447 Prepare for gTTS 2.1.0
  mycroft/tts/google_tts.py
Labels: CLA: Yes

#2443 Add test cases for the translate methods
  test/unittests/skills/test_mycroft_skill.py
  test/unittests/skills/translate/in-dialog/dialog/en-us/good_things.list
  test/unittests/skills/translate/in-dialog/dialog/en-us/named_things.value
  test/unittests/skills/translate/in-dialog/dialog/en-us/test.template
  test/unittests/skills/translate/in-locale/locale/de-de/good_things.list
  test/unittests/skills/translate/in-locale/locale/de-de/named_things.value
  test/unittests/skills/translate/in-locale/locale/de-de/test.template
  test/unittests/skills/translate/in-locale/locale/en-us/good_things.list
  test/unittests/skills/translate/in-locale/locale/en-us/named_things.value
  test/unittests/skills/translate/in-locale/locale/en-us/not_in_german.list
  test/unittests/skills/translate/in-locale/locale/en-us/test.template
Labels: CLA: Yes, type: test

#2448 Add setting for padatious single_thread in mycroft.conf
  mycroft/configuration/mycroft.conf
  mycroft/skills/padatious_service.py
Labels: CLA: Yes

#2450 Add TTS tests
  mycroft/tts/__init__.py
  mycroft/tts/bing_tts.py
  mycroft/tts/espeak_tts.py
  mycroft/tts/fa_tts.py
  mycroft/tts/google_tts.py
  mycroft/tts/ibm_tts.py
  mycroft/tts/mary_tts.py
  mycroft/tts/mimic2_tts.py
  mycroft/tts/mimic_tts.py
  mycroft/tts/remote_tts.py
  mycroft/tts/responsive_voice_tts.py
  mycroft/tts/spdsay_tts.py
  mycroft/tts/tts.py
  mycroft/tts/yandex_tts.py
  test/unittests/tts/test_google_tts.py
  test/unittests/tts/test_mimic2_tts.py
  test/unittests/tts/test_mimic_tts.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#2451 Disable failing spanish datetime test
  test/unittests/util/test_parse_es.py
Labels: CLA: Yes

#2452 Update msm to 0.8.5
  requirements.txt
Labels: CLA: Yes, tagged for review and potential merge

#2442 Add tests for the audioservice interface
  mycroft/audio/__init__.py
  mycroft/audio/audioservice.py
  mycroft/audio/services/vlc/__init__.py
  mycroft/audio/speech.py
  mycroft/audio/utils.py
  test/unittests/audio/services/working/__init__.py
  test/unittests/audio/test_service.py
  test/unittests/audio/test_simple_backend.py
  test/unittests/audio/test_speech.py
  test/unittests/audio/test_utils.py
  test/unittests/audio/test_vlc_backend.py
Labels: CLA: Yes, tagged for review and potential merge, type: test

#2453 Add readthedocs docs for settings_change_callback
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: CLA: Yes

#2415 Send mycroft.audio.queue_end
  mycroft/audio/audioservice.py
  mycroft/audio/services/simple/__init__.py
  mycroft/audio/services/vlc/__init__.py
  test/unittests/audio/test_service.py
Labels: CLA: Yes, tagged for review and potential merge

#2449 make stop-mycroft.sh also stop if skills are started from other module.
  start-mycroft.sh
  stop-mycroft.sh
Labels: CLA: Yes, tagged for review and potential merge

#2458 Upgrade to latest pip version
  dev_setup.sh
Labels: CLA: Yes, tagged for review and potential merge

#2464 Add tzinfo to extracted datetime
  mycroft/util/parse.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes
