Repository MycroftAI/mycroft-core, pull requests merged in 2020-06, with the labels that each got.

#2597 Build Snap as part of the Jenkinsfile
  Jenkinsfile
Labels: CLA: Yes

#2537 CI: Add CLA Check stage
  Jenkinsfile
Labels: CLA: Yes

#2616 self.gui.show_animated_image
  mycroft/enclosure/gui.py
  mycroft/res/ui/SYSTEM_AnimatedImageFrame.qml
Labels: CLA: Yes, Enhancement, GUI

#2583 Gentoo setup
  dev_setup.sh
Labels: CLA: Yes

#2613 Fix #2604 Add missing commands to help
  bin/mycroft-help
Labels: CLA: Yes

#2618 Add VK test - specific skill should not reply
  test/integrationtests/voight_kampff/__init__.py
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes

#2591 Workaround issue with get_wch on older ncurses
  mycroft/client/text/text_client.py
Labels: CLA: Yes, type: bug

#2621 prevent audio playing between mic record and utt handling
  mycroft/audio/audioservice.py
Labels: CLA: Yes

#2625 remove messagebus argument
  mycroft/audio/audioservice.py
Labels: CLA: Yes, type: bug
