Repository MycroftAI/mycroft-core, pull requests merged in 2020-09, with the labels that each got.

#2684 Fix vlc audioservice loading
  mycroft/audio/audioservice.py
Labels: CLA: Yes, type: bug

#2663 Voight Kampff given timeout
  test/integrationtests/voight_kampff/features/environment.py
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes

#2689 Fix Audioservice startup
  mycroft/audio/audioservice.py
  mycroft/client/speech/hotword_factory.py
  mycroft/util/monotonic_event.py
  test/unittests/util/test_monotonic_event.py
Labels: CLA: Yes

#2681 initialize status members before bus handlers
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, tagged to merge after release

#2685 Issue-2567 - Fixing not initialized dialog_render
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_mycroft_skill.py
Labels: CLA: Yes

#2688 Upgrade MSK to v0.3.16
  requirements/requirements.txt
Labels: CLA: Yes

#2682 Feat/self.gui.connected
  mycroft/client/enclosure/base.py
  mycroft/enclosure/gui.py
Labels: CLA: Yes

#2697 Add basic test cases for gui interface
  test/unittests/enclosure/__init__.py
  test/unittests/enclosure/test_gui.py
Labels: CLA: Yes

#2692 Bugfix/issue 2563
  mycroft/client/speech/hotword_factory.py
  test/unittests/client/test_local_recognizer.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#2659 Don't reload skill if a mod time is in the future
  mycroft/skills/skill_loader.py
Labels: CLA: Yes

#2599 Refactor intent service
  mycroft/skills/__main__.py
  mycroft/skills/fallback_skill.py
  mycroft/skills/intent_service.py
  mycroft/skills/intent_services/__init__.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/intent_services/base.py
  mycroft/skills/intent_services/fallback_service.py
  mycroft/skills/intent_services/padatious_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, status: in progress

#2691 Bugfix/duration stretch update
  mycroft/tts/mimic_tts.py
Labels: CLA: Yes, Status: To be reviewed, Type: Bug - complex

#2705 Remove DSS English-only error
  mycroft/stt/__init__.py
Labels: CLA: Yes

#2699 Update gtts
  requirements/requirements.txt
Labels: CLA: Yes, Status: Accepted, Type: Bug - quick
