Repository MycroftAI/mycroft-core, pull requests merged in 2020-08, with the labels that each got.

#2652 Fix settings changed check after skill handler
  mycroft/skills/mycroft_skill/mycroft_skill.py
Labels: CLA: Yes

#2649 Let lingua franca check extract_duration lang
  mycroft/util/parse.py
Labels: CLA: Yes

#2650 set active lang to configured if missing from STT and normalize
  mycroft/skills/intent_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes

#2644 Always install default skills before initial load
  mycroft/skills/skill_manager.py
  mycroft/skills/skill_updater.py
Labels: CLA: Yes

#2619 Add method for updating playback information from skills
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes, status: in review

#2654 upgrade Lingua Franca to v0.2.2
  requirements/requirements.txt
Labels: CLA: Yes

#2655 Common play information amendments
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes

#2661 Disable wake word upload for v20.2
  mycroft/client/speech/mic.py
Labels: CLA: Yes

#2662 Do not call max if files list is empty
  mycroft/skills/skill_loader.py
Labels: CLA: Yes

#2657 Allow override for animations in platform skills
  mycroft/enclosure/gui.py
Labels: CLA: Yes

#2677 Add missing watchdog argument
  mycroft/skills/__main__.py
Labels: CLA: Yes

#2674 add GUI + PAUSED to track status
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes

#2667 Remove deprecated EventEmitter classes
  mycroft/messagebus/client/threaded_event_emitter.py
  mycroft/messagebus/service/event_handler.py
  test/integrationtests/skills/skill_tester.py
  test/unittests/messagebus/client/test_threaded_event_emitter.py
  test/unittests/skills/test_event_scheduler.py
  test/wake_word/wake_word_test.py
Labels: 20.08, CLA: Yes

#2668 remove hardcoded timeouts - now in mycroft.conf
  mycroft/client/speech/mic.py
Labels: 20.08, CLA: Yes

#2669 remove previously deprecated error message
  mycroft/skills/skill_manager.py
Labels: 20.08, CLA: Yes

#2670 remove deprecated startListening signal
  mycroft/client/speech/mic.py
Labels: 20.08, CLA: Yes

#2671 remove deprecated DialogLoader class
  mycroft/dialog/__init__.py
  mycroft/dialog/dialog.py
  test/unittests/dialog/test_dialog.py
Labels: 20.08, CLA: Yes

#2672 Remove unnecessary string utils
  mycroft/util/__init__.py
  mycroft/util/audio_utils.py
  mycroft/util/string_utils.py
  test/unittests/util/test_string_utils.py
Labels: 20.08, CLA: Yes

#2673 remove deprecated speaking utils
  mycroft/util/__init__.py
Labels: 20.08, CLA: Yes

#2678 bump version numbers for 20.08
  mycroft/configuration/mycroft.conf
  mycroft/version/__init__.py
  requirements/requirements.txt
Labels: CLA: Yes

#2679 Refactor/remove imp
  mycroft/audio/audioservice.py
  test/integrationtests/skills/discover_tests.py
  test/integrationtests/skills/runner.py
Labels: CLA: Yes

#2680 Don't run default update if autoupdate is disabled
  mycroft/skills/skill_manager.py
Labels: CLA: Yes
