Repository MycroftAI/mycroft-core, pull requests merged in 2020-10, with the labels that each got.

#2704 Add optional message argument
  mycroft/skills/settings.py
Labels: CLA: Yes, Status: To be reviewed, Type: Bug - quick

#2706 Issue-2700 - Allow for different Polly engines in config
  mycroft/tts/polly_tts.py
Labels: CLA: Yes, Type: Enhancement - proposed

#2713 Feature/mozilla tts
  mycroft/configuration/mycroft.conf
  mycroft/tts/mozilla_tts.py
  mycroft/tts/tts.py
Labels: CLA: Yes, Type: Enhancement - roadmapped, hacktoberfest-accepted

#2716 Mimic arm fix
  dev_setup.sh
Labels: CLA: Yes

#2725 allow variants of arch (archarm, ...) to fetch dependencies (dev_setup.sh)
  dev_setup.sh
Labels: CLA: Yes

#2594 Plugin system for stt, tts and audioservices
  mycroft/audio/audioservice.py
  mycroft/client/speech/hotword_factory.py
  mycroft/stt/__init__.py
  mycroft/tts/tts.py
  mycroft/util/plugins.py
  test/unittests/util/test_plugins.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - roadmapped

#2721 Update __init__.py
  mycroft/lock/__init__.py
Labels: CLA: Yes

#2724 Update to pyee 8.1.0
  mycroft/client/speech/listener.py
  mycroft/messagebus/service/event_handler.py
  requirements/requirements.txt
  test/integrationtests/skills/skill_tester.py
  test/wake_word/wake_word_test.py
Labels: CLA: Yes, Type: Bug - quick

#2732 Fix/add missing skill_id parameter for page interaction and focus events
  mycroft/client/enclosure/base.py
Labels: CLA: Yes

#2731 Point sphinxdocs to new requirements.txt location
  doc/conf.py
Labels: CLA: Yes, Type: Bug - quick

#2735 ensure load_status is initialized on load failure
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, Type: Bug - quick

#2739 Run unit tests on python 3.9 as well on PRs
  .travis.yml
Labels: CLA: Yes

#2737 msm appstore warning
  mycroft/skills/msm_wrapper.py
Labels: CLA: Yes, Status: For discussion, hacktoberfest-accepted
