Repository MycroftAI/mycroft-core, pull requests merged in 2020-12, with the labels that each got.

#2766 self.gui.release()
  mycroft/enclosure/gui.py
Labels: CLA: Yes

#2767 Bugfix/anonymous adapt intent
  mycroft/skills/intent_services/adapt_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, Type: Bug - quick

#2769 Clarify that gui.clear does not close a Skill
  mycroft/enclosure/gui.py
Labels: CLA: Yes, Type: Refactoring and other improvements

#2734 skill settings sync flag
  mycroft/configuration/mycroft.conf
  mycroft/skills/settings.py
  test/unittests/mocks.py
  test/unittests/mycroft.conf
  test/util.py
Labels: CLA: Yes, Status: Change requested, hacktoberfest-accepted

#2736 Add Plugin base classes APIs to readthedocs
  doc/index.rst
  doc/source/plugins.rst
  mycroft/audio/services/__init__.py
  mycroft/client/speech/hotword_factory.py
  mycroft/stt/__init__.py
  mycroft/tts/tts.py
Labels: CLA: Yes, Type: Refactoring and other improvements

#2780 Fix UnboundLocalError in AudioProducer
  mycroft/client/speech/mic.py
Labels: CLA: Yes, Status: Accepted, Type: Bug - quick

#2782 Remove six from dependencies
  requirements/requirements.txt
Labels: CLA: Yes

#2762 Feature: enable simultaneous CI jobs and keep logs
  Jenkinsfile
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - roadmapped

#2786 fix/intent_api
  mycroft/skills/intent_service.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/intent_services/padatious_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, Type: Bug - quick
