Repository MycroftAI/mycroft-core, pull requests merged in 2020-07, with the labels that each got.

#2327 Switch from the deprecated imp to importlib
  mycroft/skills/skill_loader.py
Labels: CLA: Yes, type: feature

#2628 Add wait_for_message method
  mycroft/audio/audioservice.py
  mycroft/messagebus/client/__init__.py
  mycroft/messagebus/client/client.py
  test/unittests/messagebus/client/test_client.py
Labels: CLA: Yes, type: Code Improvements / Refactor

#2541 CI: Use the docker -f flag instead of copying the Dockerfile
  Jenkinsfile
  test/Dockerfile
Labels: CLA: Yes

#2507 Update pyee to v7.0.1
  mycroft/client/speech/listener.py
  mycroft/messagebus/client/client.py
  mycroft/messagebus/client/threaded_event_emitter.py
  requirements/requirements.txt
Labels: CLA: Yes

#2636 revert iot dig_for_message
  mycroft/skills/common_iot_skill.py
Labels: CLA: Yes

#2626 sleep after skills loaded for any final setup
  test/integrationtests/voight_kampff/features/environment.py
Labels: CLA: Yes

#2601 Service hooks
  mycroft/audio/__main__.py
  mycroft/audio/audioservice.py
  mycroft/client/enclosure/__main__.py
  mycroft/client/speech/__main__.py
  mycroft/client/speech/listener.py
  mycroft/client/speech/mic.py
  mycroft/messagebus/service/__main__.py
  mycroft/skills/__main__.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes

#2521 Fix Mimic build on Fedora
  dev_setup.sh
Labels: CLA: Needed, CLA: Yes

#2643 Add Festival TTS support
  mycroft/tts/festival_tts.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#2634 Fix custom timeout for wait_for_response()
  mycroft/messagebus/client/client.py
Labels: CLA: Yes
