Repository MycroftAI/mycroft-core, pull requests merged in 2020-05, with the labels that each got.

#2558 have a default if run without a core param
  scripts/install-mimic.sh
Labels: CLA: Yes

#2566 Polish language support
  mycroft/res/text/pl-pl/and.word
  mycroft/res/text/pl-pl/backend.down.dialog
  mycroft/res/text/pl-pl/cancel.voc
  mycroft/res/text/pl-pl/checking for updates.dialog
  mycroft/res/text/pl-pl/day.word
  mycroft/res/text/pl-pl/days.word
  mycroft/res/text/pl-pl/hour.word
  mycroft/res/text/pl-pl/hours.word
  mycroft/res/text/pl-pl/i didn't catch that.dialog
  mycroft/res/text/pl-pl/last.voc
  mycroft/res/text/pl-pl/learning disabled.dialog
  mycroft/res/text/pl-pl/learning enabled.dialog
  mycroft/res/text/pl-pl/message_loading.skills.dialog
  mycroft/res/text/pl-pl/message_rebooting.dialog
  mycroft/res/text/pl-pl/message_synching.clock.dialog
  mycroft/res/text/pl-pl/message_updating.dialog
  mycroft/res/text/pl-pl/minute.word
  mycroft/res/text/pl-pl/minutes.word
  mycroft/res/text/pl-pl/mycroft.intro.dialog
  mycroft/res/text/pl-pl/no.voc
  mycroft/res/text/pl-pl/not connected to the internet.dialog
  mycroft/res/text/pl-pl/not.loaded.dialog
  mycroft/res/text/pl-pl/or.word
  mycroft/res/text/pl-pl/phonetic_spellings.txt
  mycroft/res/text/pl-pl/reset to factory defaults.dialog
  mycroft/res/text/pl-pl/second.word
  mycroft/res/text/pl-pl/seconds.word
  mycroft/res/text/pl-pl/skill.error.dialog
  mycroft/res/text/pl-pl/skills updated.dialog
  mycroft/res/text/pl-pl/sorry I couldn't install default skills.dialog
  mycroft/res/text/pl-pl/ssh disabled.dialog
  mycroft/res/text/pl-pl/ssh enabled.dialog
  mycroft/res/text/pl-pl/time.changed.reboot.dialog
  mycroft/res/text/pl-pl/yes.voc
Labels: CLA: Yes

#2564 Bump msk to v0.3.15
  requirements.txt
Labels: CLA: Yes

#2569 Explicitely run the messagebus test with Python 3
  test/integrationtests/messagebus/messagebus_test.py
Labels: CLA: Yes

#2573 Add pytest.ini and make it ignore the wake_word directory
  pytest.ini
Labels: CLA: Yes

#2577 Bugfix/add context decorator
  mycroft/skills/context.py
  test/unittests/skills/test_context.py
Labels: CLA: Yes

#2571 Remove the xmlrunner dep from requirements.txt, it isn't actually used anymore
  requirements.txt
Labels: CLA: Yes, tagged to merge after release, type: Code Improvements / Refactor

#2582 use long options and add --upgrade to arch linux pacman
  dev_setup.sh
Labels: CLA: Yes

#2584 dev_setup.sh: add support for Alpine Linux
  dev_setup.sh
Labels: CLA: Yes

#2581 Update the ESpeak TTS plugin
  mycroft/tts/espeak_tts.py
  mycroft/tts/tts.py
  test/unittests/tts/test_espeak_tts.py
  test/unittests/tts/test_mimic_tts.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#2575 Move requirements.txt to a new requirements folder and add optional deps
  .travis.yml
  LICENSE.md
  MANIFEST.in
  dev_setup.sh
  mycroft/client/enclosure/generic/__init__.py
  requirements/extra-audiobackend.txt
  requirements/extra-mark1.txt
  requirements/extra-stt.txt
  requirements/requirements.txt
  requirements/tests.txt
  scripts/my-info.sh
  setup.py
  test/Dockerfile.test
Labels: CLA: Yes

#2585 Polly tts
  mycroft/configuration/mycroft.conf
  mycroft/tts/polly_tts.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#2559 Check the skill directory and XDG_CONFIG_DIR for settings
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/settings.py
  mycroft/skills/skill_loader.py
  requirements/requirements.txt
Labels: CLA: Yes

#2587 Revert "use long options and add --upgrade to arch linux pacman"
  dev_setup.sh
Labels: CLA: Yes

#2576 Voight kampff config given
  mycroft/configuration/config.py
  mycroft/res/text/en-us/configurations.json
  test/integrationtests/voight_kampff/features/environment.py
  test/integrationtests/voight_kampff/features/steps/configuration.py
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
  test/integrationtests/voight_kampff/test_setup.py
Labels: CLA: Yes

#2588 Bugfix/remove fallback handler
  mycroft/skills/fallback_skill.py
  test/unittests/skills/test_fallback_skill.py
Labels: CLA: Yes

#2562 Allow building Mycroft with loose requirements
  setup.py
Labels: CLA: Yes

#2592 Add 'vktest clear' command
  bin/mycroft-skill-testrunner
  start-mycroft.sh
Labels: CLA: Yes

#2595 Upgrade padatious to 0.4.8
  requirements/requirements.txt
Labels: CLA: Yes

#2598 Fix audio service startup without Internet
  mycroft/tts/google_tts.py
  test/unittests/tts/test_google_tts.py
Labels: CLA: Yes, tagged for review and potential merge, type: bug

#2589 Refactor wake-word waiting and record phrase
  mycroft/client/speech/data_structures.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/speech/mic.py
  test/unittests/client/test_data_structures.py
  test/unittests/client/test_dynamic_energy_test.py
  test/unittests/client/test_noise_tracker.py
Labels: CLA: Yes, tagged to merge after release

#2560 Refactor/settings cleanup
  mycroft/skills/settings.py
  test/unittests/skills/test_settings.py
Labels: CLA: Yes, tagged to merge after release
