Repository MycroftAI/mycroft-core, pull requests merged in 2020-04, with the labels that each got.

#2503 Bugfix Converse error
  mycroft/skills/intent_service.py
  mycroft/skills/padatious_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, type: bug

#2522 Add resource lock tests in Jenkinsfile
  Jenkinsfile
Labels: CLA: Yes

#2528 Fallback to internal version if no version file exists
  mycroft/version/__init__.py
  test/unittests/version/test_version.py
Labels: CLA: Yes

#2531 Fix standalone docs in README
  README.md
Labels: CLA: Yes

#2529 Update skill stop sequence
  mycroft/skills/audioservice.py
  mycroft/skills/skill_manager.py
  stop-mycroft.sh
Labels: CLA: Yes

#2533 Feature/gui connection update
  mycroft/client/enclosure/base.py
Labels: CLA: Yes

#2530 Feature/email jenkins results
  Jenkinsfile
Labels: CLA: Yes, type: feature

#2535 Issues-2534 - language fallback fix
  mycroft/tts/google_tts.py
Labels: CLA: Yes

#2536 Feature/mic_config - Add configuration option for microphone settings
  mycroft/client/speech/mic.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes

#2542 Move mute stage of __init__() after creating lock
  mycroft/client/speech/mic.py
Labels: CLA: Yes

#2496 Add tests for a variety of util functions
  mycroft/util/__init__.py
  mycroft/util/audio_test.py
  mycroft/util/audio_utils.py
  mycroft/util/download.py
  mycroft/util/file_utils.py
  mycroft/util/network_utils.py
  mycroft/util/platform.py
  mycroft/util/process_utils.py
  mycroft/util/signal.py
  mycroft/util/string_utils.py
  mycroft/util/time.py
  test/unittests/util/muppets.dict
  test/unittests/util/test_audio_utils.py
  test/unittests/util/test_download.py
  test/unittests/util/test_file_utils.py
  test/unittests/util/test_platform.py
  test/unittests/util/test_process_utils.py
  test/unittests/util/test_string_utils.py
  test/unittests/util/test_time.py
  test/unittests/util/unstripped_lines.txt
  test/util.py
Labels: CLA: Yes, type: Code Improvements / Refactor, type: test

#2548 Issues-2516 - Resolved IBM Cloud integration issue
  mycroft/stt/__init__.py
  test/unittests/stt/test_stt.py
Labels: CLA: Yes

#2551 Issue-2550 - Update contributor guidelines
  .github/CONTRIBUTING.md
Labels: CLA: Yes, type: documentation

#2554 Initial Czech support
  mycroft/res/text/cs-cz/and.word
  mycroft/res/text/cs-cz/backend.down.dialog
  mycroft/res/text/cs-cz/cancel.voc
  mycroft/res/text/cs-cz/checking for updates.dialog
  mycroft/res/text/cs-cz/day.word
  mycroft/res/text/cs-cz/days.word
  mycroft/res/text/cs-cz/hour.word
  mycroft/res/text/cs-cz/hours.word
  mycroft/res/text/cs-cz/i didn't catch that.dialog
  mycroft/res/text/cs-cz/last.voc
  mycroft/res/text/cs-cz/learning disabled.dialog
  mycroft/res/text/cs-cz/learning enabled.dialog
  mycroft/res/text/cs-cz/message_loading.skills.dialog
  mycroft/res/text/cs-cz/message_rebooting.dialog
  mycroft/res/text/cs-cz/message_synching.clock.dialog
  mycroft/res/text/cs-cz/message_updating.dialog
  mycroft/res/text/cs-cz/minute.word
  mycroft/res/text/cs-cz/minutes.word
  mycroft/res/text/cs-cz/mycroft.intro.dialog
  mycroft/res/text/cs-cz/no.voc
  mycroft/res/text/cs-cz/not connected to the internet.dialog
  mycroft/res/text/cs-cz/not.loaded.dialog
  mycroft/res/text/cs-cz/or.word
  mycroft/res/text/cs-cz/phonetic_spellings.txt
  mycroft/res/text/cs-cz/reset to factory defaults.dialog
  mycroft/res/text/cs-cz/second.word
  mycroft/res/text/cs-cz/seconds.word
  mycroft/res/text/cs-cz/skill.error.dialog
  mycroft/res/text/cs-cz/skills updated.dialog
  mycroft/res/text/cs-cz/sorry I couldn't install default skills.dialog
  mycroft/res/text/cs-cz/ssh disabled.dialog
  mycroft/res/text/cs-cz/ssh enabled.dialog
  mycroft/res/text/cs-cz/time.changed.reboot.dialog
  mycroft/res/text/cs-cz/yes.voc
Labels: CLA: Yes

#2555 Update pillow to the latest version
  requirements.txt
Labels: CLA: Yes
