Repository MycroftAI/mycroft-core, pull requests merged in 2020-03, with the labels that each got.

#2484 Upgrade msm to v0.8.7
  requirements.txt
Labels: CLA: Yes, tagged to merge after release

#2488 Fix resetting of converse state on STT failure
  mycroft/skills/intent_service.py
Labels: CLA: Yes, type: bug

#2491 Test reset converse
  mycroft/skills/intent_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, type: test

#2489 Bump enclosure version
  mycroft/client/enclosure/version.txt
Labels: CLA: Yes

#2429 mark1/fix display big images
  mycroft/client/enclosure/mark1/mouth.py
Labels: CLA: Yes, platform: mark1, type: bug

#2499 Enable snowboy to use several wakeword models
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes

#2479 Simplify the converse callings
  mycroft/skills/intent_service.py
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_intent_service.py
  test/unittests/skills/test_skill_manager.py
Labels: CLA: Yes, tagged to merge after release, type: Code Improvements / Refactor

#2487 Fixed typo "Devloper" to "Developer"
  dev_setup.sh
Labels: CLA: Yes

#2514 Add configurable API url to Watson TTS
  mycroft/tts/ibm_tts.py
  mycroft/tts/remote_tts.py
Labels: CLA: Yes

#2512 upgrade Lingua Franca to 0.2.1
  requirements.txt
Labels: CLA: Yes

#2515 Additional zero was prepended.
  mycroft/util/format.py
Labels: CLA: Yes

#2471 feat/ read mark1 eye color
  mycroft/client/enclosure/mark1/eyes.py
  mycroft/enclosure/api.py
Labels: CLA: Yes, Enhancement, platform: mark1

#2520 Fix danish typos and better translations
  .gitignore
  mycroft/res/text/da-dk/and.word
  mycroft/res/text/da-dk/backend.down.dialog
  mycroft/res/text/da-dk/cancel.voc
  mycroft/res/text/da-dk/checking for updates.dialog
  mycroft/res/text/da-dk/day.word
  mycroft/res/text/da-dk/days.word
  mycroft/res/text/da-dk/hour.word
  mycroft/res/text/da-dk/hours.word
  mycroft/res/text/da-dk/i didn't catch that.dialog
  mycroft/res/text/da-dk/last.voc
  mycroft/res/text/da-dk/learning disabled.dialog
  mycroft/res/text/da-dk/learning enabled.dialog
  mycroft/res/text/da-dk/message_loading.skills.dialog
  mycroft/res/text/da-dk/message_rebooting.dialog
  mycroft/res/text/da-dk/message_synching.clock.dialog
  mycroft/res/text/da-dk/message_updating.dialog
  mycroft/res/text/da-dk/minute.word
  mycroft/res/text/da-dk/minutes.word
  mycroft/res/text/da-dk/mycroft.intro.dialog
  mycroft/res/text/da-dk/no.voc
  mycroft/res/text/da-dk/not connected to the internet.dialog
  mycroft/res/text/da-dk/not.loaded.dialog
  mycroft/res/text/da-dk/or.word
  mycroft/res/text/da-dk/phonetic_spellings.txt
  mycroft/res/text/da-dk/reset to factory defaults.dialog
  mycroft/res/text/da-dk/second.word
  mycroft/res/text/da-dk/seconds.word
  mycroft/res/text/da-dk/skill.error.dialog
  mycroft/res/text/da-dk/skills updated.dialog
  mycroft/res/text/da-dk/sorry I couldn't install default skills.dialog
  mycroft/res/text/da-dk/ssh disabled.dialog
  mycroft/res/text/da-dk/ssh enabled.dialog
  mycroft/res/text/da-dk/time.changed.reboot.dialog
  mycroft/res/text/da-dk/yes.voc
Labels: CLA: Yes
