Repository MycroftAI/mycroft-core, pull requests merged in 2021-05, with the labels that each got.

#2894 Old skill tester: Fix Padatious setup and fallback intents
  test/integrationtests/skills/skill_tester.py
Labels: CLA: Yes, Type: Bug - quick, Type: Tests

#2897 Fix news no stop
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes

#2899 Fix replacement of existing Skill loader in queue
  mycroft/skills/skill_manager.py
  test/unittests/skills/test_skill_manager.py
Labels: CLA: Yes, Type: Bug - quick

#2892 Replace hardcoded use of /tmp directory
  mycroft/client/enclosure/mark1/__init__.py
  mycroft/lock/__init__.py
  mycroft/skills/msm_wrapper.py
  mycroft/skills/skill_updater.py
  mycroft/tts/tts.py
  mycroft/util/__init__.py
  mycroft/util/audio_test.py
  mycroft/util/file_utils.py
  test/unittests/audio/test_utils.py
  test/unittests/lock/test_lock.py
  test/unittests/util/test_audio_utils.py
  test/unittests/util/test_download.py
  test/unittests/util/test_file_utils.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - proposed

#2890 Upgrade Lingua Franca to v0.4.1
  doc/source/mycroft.util.format.rst
  doc/source/mycroft.util.parse.rst
  mycroft/configuration/__init__.py
  mycroft/configuration/locale.py
  mycroft/skills/__main__.py
  mycroft/skills/intent_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_manager.py
  mycroft/util/format.py
  mycroft/util/parse.py
  requirements/requirements.txt
  test/unittests/skills/test_mycroft_skill_get_response.py
  test/unittests/util/test_format.py
  test/unittests/util/test_parse.py
Labels: CLA: Yes

#2907 Bump core version and MSM for impending core update
  mycroft/configuration/mycroft.conf
  mycroft/version/__init__.py
  requirements/requirements.txt
Labels: CLA: Yes

#2909 Update Adapt intent parser from v0.3.7 to v0.4.1
  requirements/requirements.txt
Labels: CLA: Yes

#2888 Refactor mimic_tts to not load config when importing
  mycroft/tts/mimic_tts.py
  test/unittests/tts/test_mimic_tts.py
Labels: CLA: Yes, Merge after next release, Status: Accepted, Type: Refactoring and other improvements

#2903 ReadTheDocs documentation: Fetch Mycroft-core version from mycroft.version
  doc/conf.py
Labels: CLA: Yes, Merge after next release, Type: Refactoring and other improvements
