Repository MycroftAI/mycroft-core, pull requests merged in 2021-02, with the labels that each got.

#2815 Bug Fix - Use the correct delegate, fix layouts, autofit text for System TextFrame
  mycroft/res/ui/SYSTEM_TextFrame.qml
Labels: CLA: Yes, Status: To be reviewed, Type: Bug - quick

#2821 Refactor/stop speaking
  mycroft/audio/utils.py
  test/unittests/audio/test_simple_backend.py
  test/unittests/audio/test_utils.py
Labels: CLA: Yes, Status: Accepted

#2823 Reorder operations to ensure removed Skills are first unloaded.
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, Type: Bug - quick

#2820 Feature/gui get
  mycroft/enclosure/gui.py
  test/unittests/enclosure/test_gui.py
Labels: CLA: Yes, Status: For discussion, Type: Enhancement - proposed, Type: Tests

#2690 Add support for `doas`
  dev_setup.sh
Labels: CLA: Yes, Status: For Voting, Status: To be reviewed, Type: Enhancement - proposed

#2828 Add Mozilla TTS connection validation
  mycroft/configuration/mycroft.conf
  mycroft/tts/mozilla_tts.py
Labels: CLA: Yes

#2829 Send correct conf to mimic when used as fallback
  .github/workflows/unit_test.yml
  mycroft/tts/tts.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#2831 Upgrade gTTS to fix Google voice
  mycroft/tts/google_tts.py
  requirements/requirements.txt
  test/unittests/tts/test_google_tts.py
Labels: CLA: Yes, Status: To be reviewed, Type: Bug - quick

#1822 Feature/skill api
  mycroft/client/text/text_client.py
  mycroft/skills/__init__.py
  mycroft/skills/__main__.py
  mycroft/skills/api.py
  mycroft/skills/mycroft_skill/__init__.py
  mycroft/skills/mycroft_skill/decorators.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_skill_api.py
Labels: CLA: Yes, Status: Accepted, Type: Enhancement - roadmapped
