Repository MycroftAI/mycroft-core, pull requests merged in 2021-11, with the labels that each got.

#3021 Azerbaijani language support
  mycroft/res/text/az-az/and.word
  mycroft/res/text/az-az/backend.down.dialog
  mycroft/res/text/az-az/cancel.voc
  mycroft/res/text/az-az/checking for updates.dialog
  mycroft/res/text/az-az/day.word
  mycroft/res/text/az-az/hour.word
  mycroft/res/text/az-az/i didn't catch that.dialog
  mycroft/res/text/az-az/last.voc
  mycroft/res/text/az-az/message_loading.skills.dialog
  mycroft/res/text/az-az/message_rebooting.dialog
  mycroft/res/text/az-az/message_synching.clock.dialog
  mycroft/res/text/az-az/message_updating.dialog
  mycroft/res/text/az-az/minute.word
  mycroft/res/text/az-az/mycroft.intro.dialog
  mycroft/res/text/az-az/no.voc
  mycroft/res/text/az-az/not connected to the internet.dialog
  mycroft/res/text/az-az/not.loaded.dialog
  mycroft/res/text/az-az/or.word
  mycroft/res/text/az-az/phonetic_spellings.txt
  mycroft/res/text/az-az/reset to factory defaults.dialog
  mycroft/res/text/az-az/second.word
  mycroft/res/text/az-az/skill.error.dialog
  mycroft/res/text/az-az/skills updated.dialog
  mycroft/res/text/az-az/sorry I couldn't install default skills.dialog
  mycroft/res/text/az-az/time.changed.reboot.dialog
  mycroft/res/text/az-az/yes.voc
Labels: CLA: Yes

#3019 Refactor/shellcheck bin
  .github/workflows/unit_test.yml
  bin/mycroft-cli-client
  bin/mycroft-config
  bin/mycroft-help
  bin/mycroft-listen
  bin/mycroft-mic-test
  bin/mycroft-msk
  bin/mycroft-msm
  bin/mycroft-pip
  bin/mycroft-say-to
  bin/mycroft-skill-testrunner
  bin/mycroft-speak
  bin/mycroft-start
  bin/mycroft-stop
Labels: CLA: Yes

#3022 Fix race condition in GUI namespace insertion
  mycroft/client/enclosure/base.py
Labels: CLA: Yes, Type: Bug - quick

#3020 Added Possibility for ESpeak Config
  mycroft/tts/espeak_tts.py
Labels: CLA: Yes, hacktoberfest-accepted

#3028 Update link for Hub to point to official Github version
  .github/CONTRIBUTING.md
Labels: CLA: Yes

#3036 Remove incorrectly added args in GUIWebsocketHandler methods
  mycroft/client/enclosure/base.py
Labels: CLA: Yes, Type: Bug - quick

#3025 Check if GUI is connected rather than maintain list of platforms
  mycroft/skills/common_query_skill.py
  test/unittests/skills/test_common_query_skill.py
Labels: CLA: Yes, Type: Bug - quick

#3039 Issue-3026 - Update Gentoo libffi dependency reference
  dev_setup.sh
Labels: CLA: Yes

#3042 Issue-3041 - Install pip for python version specified by argument in …
  dev_setup.sh
Labels: CLA: Yes

#3033 Fix config priority
  mycroft/configuration/config.py
  mycroft/util/log.py
Labels: CLA: Yes

#3045 Do not create configs folders until writing
  mycroft/client/enclosure/mark1/__init__.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/text/text_client.py
  mycroft/configuration/config.py
  mycroft/configuration/locations.py
Labels: CLA: Yes
