Repository MycroftAI/mycroft-core, pull requests merged in 2021-09, with the labels that each got.

#2985 Add warning for anyone loading GoogleTTS
  mycroft/tts/google_tts.py
Labels: CLA: Yes

#2996 Patch dependencies that use the deprecated use_2to3
  requirements/tests.txt
Labels: CLA: Yes, Type: Bug - quick

#2992 Fix pulseaudio daemon failing to start in CI
  test/integrationtests/voight_kampff/run_test_suite.sh
Labels: CLA: Yes

#2990 Fix messages clearing in the InterceptAllBusClient
  test/integrationtests/voight_kampff/features/environment.py
Labels: CLA: Yes

#2979 Release GUI on Skill shutdown or reload
  mycroft/enclosure/gui.py
Labels: CLA: Yes

#2997 Add 'utterances' to message emitted to skill intent handler
  mycroft/skills/intent_service.py
Labels: CLA: Yes, CLA: Needed

#2975 VK: Only stop Mycroft services if running in CI
  test/integrationtests/voight_kampff/run_test_suite.sh
Labels: CLA: Yes, Status: Accepted

#3001 fixed an error with message formatting in a ValueError message
  test/integrationtests/voight_kampff/features/environment.py
Labels: CLA: Yes

#2986 Improve confidence calculation for Common Query
  mycroft/res/text/en-us/noise_words.list
  mycroft/skills/common_query_skill.py
  test/unittests/skills/test_common_query_skill.py
Labels: CLA: Yes

#2963 Update key names in adapt keyword registration message
  mycroft/skills/intent_service.py
  mycroft/skills/intent_service_interface.py
  mycroft/skills/intent_services/adapt_service.py
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_intent_service.py
  test/unittests/skills/test_intent_service_interface.py
  test/unittests/skills/test_mycroft_skill.py
Labels: CLA: Yes

#3000 alter avx test to accomodate aarch64
  dev_setup.sh
Labels: CLA: Yes
