Repository MycroftAI/mycroft-core, pull requests merged in 2021-03, with the labels that each got.

#2843 fix/padatious_mess
  mycroft/skills/padatious_service.py
Labels: CLA: Yes, Status: Accepted

#2840 Issue-2750 - Remove log pollution
  mycroft/skills/skill_manager.py
Labels: CLA: Yes

#2841 dev_setup.sh: install Alpine deps to a virtual meta package
  dev_setup.sh
Labels: CLA: Yes

#2844 Remove example entries in blacklisted_skills config
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, Type: Bug - quick

#2838 get response tests
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/mocks.py
  test/unittests/skills/test_common_play_skill.py
  test/unittests/skills/test_common_query_skill.py
  test/unittests/skills/test_mycroft_skill_get_response.py
  test/unittests/skills/test_skill/dialog/en-us/what do you want.dialog
Labels: CLA: Yes, Type: Tests

#2813 Issue-2812 - Allow overridden converse methods to accept messages
  mycroft/skills/mycroft_skill/mycroft_skill.py
  mycroft/skills/skill_manager.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - proposed

#2849 Remove intent-service backwards compatibilities
  mycroft/skills/__main__.py
  mycroft/skills/fallback_skill.py
  mycroft/skills/intent_service.py
  test/unittests/skills/test_intent_service.py
Labels: CLA: Yes, Type: Refactoring and other improvements

#2853 Consolidate TTS cache logic
  mycroft/audio/speech.py
  mycroft/tts/cache.py
  mycroft/tts/cache_handler.py
  mycroft/tts/mimic2_tts.py
  mycroft/tts/tts.py
  test/unittests/res/text/en-us/test.dialog
  test/unittests/res/text/en-us/test.word
  test/unittests/res/text/en-us/test_message.dialog
  test/unittests/tts/test_cache.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#2857 Fix dev_setup.sh max cores detection
  dev_setup.sh
Labels: CLA: Yes, Type: Bug - quick

#2856 Remove stray print
  mycroft/skills/mycroft_skill/event_container.py
Labels: CLA: Yes, Type: Refactoring and other improvements

#2783 Upgrade requests to 2.25.1
  requirements/requirements.txt
Labels: CLA: Yes

#2865 The phoneme needs to be converted to a list before being passed on.
  mycroft/tts/cache.py
Labels: CLA: Yes

#2858 Add exact optional param to voc_match
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/unittests/skills/test_mycroft_skill.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - roadmapped

#2869 Move TTS cache curation to TextToSpeechCache
  mycroft/tts/cache.py
  mycroft/tts/tts.py
  test/unittests/tts/test_cache.py
Labels: CLA: Yes

#2870 Sync curated cache with dict of cached sentences
  mycroft/tts/cache.py
  mycroft/util/file_utils.py
  test/unittests/tts/test_cache.py
  test/unittests/util/test_file_utils.py
Labels: CLA: Yes, Type: Bug - quick

#2863 Utilize the mycroft-messagebus-client module
  mycroft/messagebus/client/__init__.py
  mycroft/messagebus/client/client.py
  mycroft/messagebus/message.py
  mycroft/skills/mycroft_skill/event_container.py
  requirements/requirements.txt
Labels: CLA: Yes, Status: For discussion, Type: Refactoring and other improvements
