Repository MycroftAI/mycroft-core, pull requests merged in 2021-07, with the labels that each got.

#2937 Fix VK race condition in MycroftSkill.get_response()
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
Labels: CLA: Yes

#2939 Fix bargein
  mycroft/audio/speech.py
  mycroft/client/speech/__main__.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#2778 fa-ir localization initialized
  mycroft/res/text/fa-ir/and.word
  mycroft/res/text/fa-ir/backend.down.dialog
  mycroft/res/text/fa-ir/cancel.voc
  mycroft/res/text/fa-ir/checking for updates.dialog
  mycroft/res/text/fa-ir/day.word
  mycroft/res/text/fa-ir/days.word
  mycroft/res/text/fa-ir/hour.word
  mycroft/res/text/fa-ir/hours.word
  mycroft/res/text/fa-ir/i didn't catch that.dialog
  mycroft/res/text/fa-ir/last.voc
  mycroft/res/text/fa-ir/learning disabled.dialog
  mycroft/res/text/fa-ir/learning enabled.dialog
  mycroft/res/text/fa-ir/message_loading.skills.dialog
  mycroft/res/text/fa-ir/message_rebooting.dialog
  mycroft/res/text/fa-ir/message_synching.clock.dialog
  mycroft/res/text/fa-ir/message_updating.dialog
  mycroft/res/text/fa-ir/minute.word
  mycroft/res/text/fa-ir/minutes.word
  mycroft/res/text/fa-ir/mycroft.intro.dialog
  mycroft/res/text/fa-ir/no.voc
  mycroft/res/text/fa-ir/not connected to the internet.dialog
  mycroft/res/text/fa-ir/not.loaded.dialog
  mycroft/res/text/fa-ir/or.word
  mycroft/res/text/fa-ir/phonetic_spellings.txt
  mycroft/res/text/fa-ir/reset to factory defaults.dialog
  mycroft/res/text/fa-ir/second.word
  mycroft/res/text/fa-ir/seconds.word
  mycroft/res/text/fa-ir/skill.error.dialog
  mycroft/res/text/fa-ir/skills updated.dialog
  mycroft/res/text/fa-ir/sorry I couldn't install default skills.dialog
  mycroft/res/text/fa-ir/ssh disabled.dialog
  mycroft/res/text/fa-ir/ssh enabled.dialog
  mycroft/res/text/fa-ir/time.changed.reboot.dialog
  mycroft/res/text/fa-ir/yes.voc
Labels: CLA: Yes, Status: Work in progress, Type: Enhancement - proposed

#2942 Revert "fa-ir localization initialized (#2778)"
  mycroft/res/text/fa-ir/and.word
  mycroft/res/text/fa-ir/backend.down.dialog
  mycroft/res/text/fa-ir/cancel.voc
  mycroft/res/text/fa-ir/checking for updates.dialog
  mycroft/res/text/fa-ir/day.word
  mycroft/res/text/fa-ir/days.word
  mycroft/res/text/fa-ir/hour.word
  mycroft/res/text/fa-ir/hours.word
  mycroft/res/text/fa-ir/i didn't catch that.dialog
  mycroft/res/text/fa-ir/last.voc
  mycroft/res/text/fa-ir/learning disabled.dialog
  mycroft/res/text/fa-ir/learning enabled.dialog
  mycroft/res/text/fa-ir/message_loading.skills.dialog
  mycroft/res/text/fa-ir/message_rebooting.dialog
  mycroft/res/text/fa-ir/message_synching.clock.dialog
  mycroft/res/text/fa-ir/message_updating.dialog
  mycroft/res/text/fa-ir/minute.word
  mycroft/res/text/fa-ir/minutes.word
  mycroft/res/text/fa-ir/mycroft.intro.dialog
  mycroft/res/text/fa-ir/no.voc
  mycroft/res/text/fa-ir/not connected to the internet.dialog
  mycroft/res/text/fa-ir/not.loaded.dialog
  mycroft/res/text/fa-ir/or.word
  mycroft/res/text/fa-ir/phonetic_spellings.txt
  mycroft/res/text/fa-ir/reset to factory defaults.dialog
  mycroft/res/text/fa-ir/second.word
  mycroft/res/text/fa-ir/seconds.word
  mycroft/res/text/fa-ir/skill.error.dialog
  mycroft/res/text/fa-ir/skills updated.dialog
  mycroft/res/text/fa-ir/sorry I couldn't install default skills.dialog
  mycroft/res/text/fa-ir/ssh disabled.dialog
  mycroft/res/text/fa-ir/ssh enabled.dialog
  mycroft/res/text/fa-ir/time.changed.reboot.dialog
  mycroft/res/text/fa-ir/yes.voc
Labels: CLA: Yes

#2943 fa-ir localization initialized
  mycroft/res/text/fa-ir/and.word
  mycroft/res/text/fa-ir/backend.down.dialog
  mycroft/res/text/fa-ir/cancel.voc
  mycroft/res/text/fa-ir/checking for updates.dialog
  mycroft/res/text/fa-ir/day.word
  mycroft/res/text/fa-ir/days.word
  mycroft/res/text/fa-ir/hour.word
  mycroft/res/text/fa-ir/hours.word
  mycroft/res/text/fa-ir/i didn't catch that.dialog
  mycroft/res/text/fa-ir/last.voc
  mycroft/res/text/fa-ir/learning disabled.dialog
  mycroft/res/text/fa-ir/learning enabled.dialog
  mycroft/res/text/fa-ir/message_loading.skills.dialog
  mycroft/res/text/fa-ir/message_rebooting.dialog
  mycroft/res/text/fa-ir/message_synching.clock.dialog
  mycroft/res/text/fa-ir/message_updating.dialog
  mycroft/res/text/fa-ir/minute.word
  mycroft/res/text/fa-ir/minutes.word
  mycroft/res/text/fa-ir/mycroft.intro.dialog
  mycroft/res/text/fa-ir/no.voc
  mycroft/res/text/fa-ir/not connected to the internet.dialog
  mycroft/res/text/fa-ir/not.loaded.dialog
  mycroft/res/text/fa-ir/or.word
  mycroft/res/text/fa-ir/phonetic_spellings.txt
  mycroft/res/text/fa-ir/reset to factory defaults.dialog
  mycroft/res/text/fa-ir/second.word
  mycroft/res/text/fa-ir/seconds.word
  mycroft/res/text/fa-ir/skill.error.dialog
  mycroft/res/text/fa-ir/skills updated.dialog
  mycroft/res/text/fa-ir/sorry I couldn't install default skills.dialog
  mycroft/res/text/fa-ir/ssh disabled.dialog
  mycroft/res/text/fa-ir/ssh enabled.dialog
  mycroft/res/text/fa-ir/time.changed.reboot.dialog
  mycroft/res/text/fa-ir/yes.voc
Labels: CLA: Yes

#2945 Added comments to document race condition
  mycroft/skills/mycroft_skill/mycroft_skill.py
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
Labels: CLA: Yes

#2938 Fix TTS using the returned path
  mycroft/tts/tts.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#2927 stop passing lang=None to Lingua Franca
  mycroft/util/format.py
  mycroft/util/parse.py
Labels: CLA: Yes

#2807 Add update comment logic to Jenkins
  Jenkinsfile
Labels: CLA: Yes, Status: For discussion

#2954 VK: Remove mycroft-stock from install list
  test/integrationtests/voight_kampff/default.yml
Labels: CLA: Yes, Type: Bug - quick, Type: Tests

#2957 Fix loading of audioservice plugins
  mycroft/audio/audioservice.py
Labels: CLA: Yes, Type: Bug - quick
