Repository MycroftAI/mycroft-core, pull requests merged in 2021-01, with the labels that each got.

#2707 Fix remote settings overwrite at startup
  mycroft/skills/settings.py
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - proposed

#2790 Unshadow Message class in _handle_pairing_complete
  mycroft/client/enclosure/generic/__init__.py
Labels: CLA: Yes

#2785 docs: fix simple typo, retruns -> returns
  mycroft/skills/skill_data.py
Labels: CLA: Yes

#2791 bug/vlc --no-video
  mycroft/audio/services/vlc/__init__.py
Labels: CLA: Yes

#2758 Ensure messagebus is connected before reporting that the service is ready
  mycroft/client/enclosure/__main__.py
  mycroft/client/enclosure/base.py
  mycroft/services/__init__.py
  mycroft/services/util.py
Labels: CLA: Yes, Status: Work in progress

#2788 Do not download Precise if executable already exists
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes

#2793 Vk error stability
  test/integrationtests/voight_kampff/features/steps/configuration.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes

#2781 Fix missing remove page implementation, show idle if all pages removed
  mycroft/client/enclosure/base.py
  mycroft/enclosure/gui.py
Labels: CLA: Yes, Status: Change requested, Type: Bug - quick

#2800 Fix Mimic 2 cache directory error
  mycroft/tts/cache_handler.py
Labels: CLA: Yes, Status: Change requested, Type: Bug - quick

#2792 Refactor - common bus connection method
  mycroft/audio/__main__.py
  mycroft/audio/audioservice.py
  mycroft/client/enclosure/base.py
  mycroft/client/speech/__main__.py
  mycroft/services/__init__.py
  mycroft/services/util.py
  mycroft/skills/__main__.py
  mycroft/util/__init__.py
  mycroft/util/process_utils.py
  test/unittests/audio/test_service.py
Labels: CLA: Yes, Status: Change requested

#2808 Add VK method to wait for audio service
  test/integrationtests/voight_kampff/__init__.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes, Type: Enhancement - proposed

#2805 Docs/filesystem
  doc/conf.py
  doc/requirements.txt
  doc/source/mycroft.filesystem.rst
  doc/source/mycroft.rst
  mycroft/filesystem/__init__.py
Labels: CLA: Yes, Status: Accepted

#2809 Stop location being referenced before assignment
  mycroft/configuration/config.py
Labels: CLA: Yes, Type: Bug - quick

#2722 Update for newer Porcupine engines
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes, Status: To be reviewed, Type: Bug - quick

#2648 Improve readiness check for all services
  mycroft/audio/__main__.py
  mycroft/client/enclosure/generic/__init__.py
  mycroft/client/speech/__main__.py
  mycroft/skills/__main__.py
  mycroft/skills/intent_services/padatious_service.py
  mycroft/skills/padatious_service.py
  mycroft/skills/skill_manager.py
  mycroft/util/process_utils.py
  test/unittests/skills/test_skill_manager.py
  test/unittests/util/test_process_utils.py
Labels: CLA: Yes, Status: Accepted, Type: Enhancement - roadmapped

#2804 Bugfix/audioservice issues
  mycroft/audio/audioservice.py
  mycroft/audio/services/simple/__init__.py
  mycroft/tts/dummy_tts.py
Labels: CLA: Yes, Type: Bug - quick, Type: Tests

#2819 Implement GitHub Actions for linting and unit tests
  .coveralls.yml
  .github/workflows/unit_test.yml
  .travis.yml
  README.md
  dev_setup.sh
Labels: CLA: Yes
