Repository MycroftAI/mycroft-core, pull requests merged in 2021-12, with the labels that each got.

#3014 Update Russian words and dialogues
  mycroft/res/text/ru-ru/and.word
  mycroft/res/text/ru-ru/backend.down.dialog
  mycroft/res/text/ru-ru/cancel.voc
  mycroft/res/text/ru-ru/checking for updates.dialog
  mycroft/res/text/ru-ru/days.word
  mycroft/res/text/ru-ru/hours.word
  mycroft/res/text/ru-ru/i didn't catch that.dialog
  mycroft/res/text/ru-ru/last.voc
  mycroft/res/text/ru-ru/learning disabled.dialog
  mycroft/res/text/ru-ru/learning enabled.dialog
  mycroft/res/text/ru-ru/message_loading.skills.dialog
  mycroft/res/text/ru-ru/message_rebooting.dialog
  mycroft/res/text/ru-ru/message_synching.clock.dialog
  mycroft/res/text/ru-ru/message_updating.dialog
  mycroft/res/text/ru-ru/minutes.word
  mycroft/res/text/ru-ru/mycroft.intro.dialog
  mycroft/res/text/ru-ru/no.voc
  mycroft/res/text/ru-ru/not connected to the internet.dialog
  mycroft/res/text/ru-ru/not.loaded.dialog
  mycroft/res/text/ru-ru/or.word
  mycroft/res/text/ru-ru/phonetic_spellings.txt
  mycroft/res/text/ru-ru/reset to factory defaults.dialog
  mycroft/res/text/ru-ru/second.word
  mycroft/res/text/ru-ru/seconds.word
  mycroft/res/text/ru-ru/skill.error.dialog
  mycroft/res/text/ru-ru/skills updated.dialog
  mycroft/res/text/ru-ru/sorry I couldn't install default skills.dialog
  mycroft/res/text/ru-ru/ssh disabled.dialog
  mycroft/res/text/ru-ru/ssh enabled.dialog
  mycroft/res/text/ru-ru/time.changed.reboot.dialog
  mycroft/res/text/ru-ru/yes.voc
Labels: CLA: Yes

#3030 Use shellcheck directive instead of excludes
  .github/workflows/unit_test.yml
  .shellcheckrc
  bin/mycroft-config
  bin/mycroft-help
  bin/mycroft-say-to
  bin/mycroft-skill-testrunner
  bin/mycroft-speak
Labels: CLA: Yes, Merge after next release

#3043 Update pyxdg to ensure Python3.8 compatibility
  requirements/requirements.txt
Labels: CLA: Yes, Merge after next release, Type: Bug - quick

#3047 Do not create identity folder when trying to read the identity file
  mycroft/identity/__init__.py
Labels: CLA: Yes
