Repository MycroftAI/mycroft-core, pull requests merged in 2021-06, with the labels that each got.

#2910 Check for the AVX instruction set during install
  dev_setup.sh
  mycroft/client/speech/hotword_factory.py
  mycroft/configuration/mycroft.conf
Labels: CLA: Yes, Status: To be reviewed, Type: Enhancement - proposed

#2741 revert a temporary bugfix from PR #2626
  test/integrationtests/voight_kampff/features/environment.py
Labels: CLA: Yes, Status: To be reviewed

#2914 Make TTSCache safer
  mycroft/tts/cache.py
  mycroft/tts/tts.py
  test/unittests/tts/test_cache.py
Labels: CLA: Yes, Type: Bug - quick

#2908 Upgrade Lingua Franca from v0.4.1 > v0.4.2
  requirements/requirements.txt
Labels: CLA: Yes, Status: To be reviewed

#2693 Fix broken link in Contributor Guide
  .github/CONTRIBUTING.md
Labels: CLA: Yes, Status: To be reviewed, Type: Refactoring and other improvements

#2715 Fix #1943 - do not attempt update when only launching CLI
  start-mycroft.sh
Labels: CLA: Yes, Status: Change requested, Type: Enhancement - proposed, hacktoberfest-accepted

#2931 Stop creation of 'None' cache directory
  mycroft/tts/cache.py
Labels: CLA: Yes, Type: Bug - quick

#2936 Remove docs encouraging Skill config via mycroft.conf
  README.md
Labels: CLA: Yes

#2900 Add Common Play to active Skills when invoked
  mycroft/skills/common_play_skill.py
Labels: CLA: Yes

#2934 Fix #2929: use returned TTS audio file path
  mycroft/tts/tts.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes
