Repository MycroftAI/mycroft-core, pull requests merged in 2021-08, with the labels that each got.

#2962 Make network tests configurable
  mycroft/configuration/mycroft.conf
  mycroft/util/network_utils.py
  test/unittests/util/test_network_utils.py
Labels: CLA: Yes

#2960 Upgrade Adapt to v0.5.1
  requirements/requirements.txt
Labels: CLA: Yes

#2956 Add feature request functionality to webviews
  mycroft/res/ui/FeatureRequest.qml
  mycroft/res/ui/RequestHandler.qml
  mycroft/res/ui/WebViewHtmlFrame.qml
  mycroft/res/ui/WebViewUrlFrame.qml
Labels: CLA: Yes

#2944 Use unique paths for temp file storage
  Jenkinsfile
Labels: CLA: Yes

#2946 Improve the speed of waiting for dialogs helper function
  mycroft/skills/intent_services/adapt_service.py
  test/integrationtests/voight_kampff/__init__.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes

#2948 Fix Possible vk message race
  test/integrationtests/voight_kampff/features/environment.py
Labels: CLA: Yes, Type: Bug - quick, Type: Tests

#2951 Use event handler to capture messages in then_wait()
  test/integrationtests/voight_kampff/features/environment.py
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
  test/integrationtests/voight_kampff/tools.py
Labels: CLA: Yes, Type: Tests

#2794 Pure-try-out's XDG config PR with changed Jenkinsfile
  Jenkinsfile
  README.md
  bin/mycroft-config
  mycroft/__init__.py
  mycroft/api/__init__.py
  mycroft/client/enclosure/__main__.py
  mycroft/client/enclosure/mark1/__init__.py
  mycroft/client/speech/hotword_factory.py
  mycroft/client/text/text_client.py
  mycroft/configuration/config.py
  mycroft/configuration/locations.py
  mycroft/configuration/mycroft.conf
  mycroft/filesystem/__init__.py
  mycroft/messagebus/send_func.py
  mycroft/skills/event_scheduler.py
  mycroft/skills/skill_updater.py
  mycroft/util/file_utils.py
  mycroft/util/log.py
  test/unittests/skills/test_skill_updater.py
  test/unittests/util/commented.json
  test/unittests/util/plain.json
Labels: CLA: Yes

#2968 Voight Kampff: No skill updates at runtime
  test/Dockerfile
Labels: CLA: Yes

#2967 add fullscreen fix for webviews
  mycroft/res/ui/WebViewHtmlFrame.qml
  mycroft/res/ui/WebViewUrlFrame.qml
Labels: CLA: Yes

#2970 Provide AdaptIntent from mycroft.skills
  mycroft/skills/__init__.py
Labels: Type: Enhancement - proposed, Status: To be reviewed, CLA: Yes

#2971 Install pulseaudio-utils on Fedora
  dev_setup.sh
Labels: CLA: Yes, Type: Bug - quick, Status: Accepted

#2966 scripts: Support busybox chown
  scripts/mycroft-use.sh
Labels: CLA: Yes
