Repository MycroftAI/mycroft-core, pull requests merged in 2022-02, with the labels that each got.

#3073 dev_setup.sh: Select the proper get-pip url for Python 3.6
  dev_setup.sh
Labels: CLA: Yes

#3077 Switch CLA Checker to new credentials
  Jenkinsfile
Labels: CLA: Yes

#3065 Fix: show text delegate as per autofit label refactor
  mycroft/res/ui/SYSTEM_TextFrame.qml
Labels: CLA: Yes

#3049 Remove ResponsiveVoice TTS module from core
  mycroft/configuration/mycroft.conf
  mycroft/tts/responsive_voice_tts.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#3023 Add phonetic spellings for IP and Wikipedia
  mycroft/res/text/en-us/phonetic_spellings.txt
Labels: Type: Enhancement - proposed, CLA: Yes

#3071 Added duration_to_bytes to FileMockMicrophone
  test/wake_word/wake_word_test.py
Labels: CLA: Yes, Type: Tests

#3068 Voigt kampff: Bugfix dialogfile from sentence
  test/integrationtests/voight_kampff/features/steps/utterance_responses.py
Labels: CLA: Yes, Type: Tests

#3060 Use double bracket for shell conditional
  dev_setup.sh
Labels: CLA: Yes, Type: Bug - quick

#3061 Add initial value for shell variable
  dev_setup.sh
Labels: CLA: Yes, Type: Bug - quick

#3054 Bugfix/handle missing noise words
  mycroft/skills/common_query_skill.py
Labels: CLA: Yes, Type: Bug - quick

#3057 Add noise_words.list for Swedish
  mycroft/res/text/sv-se/noise_words.list
Labels: CLA: Yes

#3078 Remove mplayer audioservice
  mycroft/audio/services/mplayer/__init__.py
Labels: CLA: Yes

#3063 Shellcheck scripts folder
  .github/workflows/unit_test.yml
  dev_setup.sh
  scripts/install-mimic.sh
  scripts/install-pocketsphinx.sh
  scripts/install-pygtk.sh
  scripts/my-info.sh
  scripts/mycroft-use.sh
  scripts/prepare-msm.sh
Labels: CLA: Yes

#3059 Add `supported_languages` parameter to STT and TTS base classes
  mycroft/stt/__init__.py
  mycroft/tts/tts.py
Labels: CLA: Yes

#3080 Fix pip url for Python > 3.6
  dev_setup.sh
Labels: CLA: Yes

#3081 Bump requests to remove GPL from dependency tree
  requirements/requirements.txt
Labels: CLA: Yes

#3031 Remove inflection dependency
  mycroft/configuration/config.py
  requirements/requirements.txt
Labels: Type: Enhancement - proposed, CLA: Yes
