Repository MycroftAI/mycroft-core, pull requests merged in 2022-03, with the labels that each got.

#3055 Backport/playback queue singleton
  mycroft/audio/speech.py
  mycroft/tts/mimic_tts.py
  mycroft/tts/tts.py
  test/unittests/audio/test_speech.py
  test/unittests/tts/test_tts.py
Labels: CLA: Yes

#3082 Send python version detection output to /dev/null
  dev_setup.sh
Labels: CLA: Yes

#2881 Don't overwrite invalid json
  mycroft/configuration/config.py
  test/unittests/configuration/test_configuration.py
Labels: Status: To be reviewed, CLA: Yes

#3086 Remove skills dir symlink on --clean
  dev_setup.sh
Labels: CLA: Yes

#3088 Fix inconsistent hotwords configuration reference
  mycroft/client/speech/hotword_factory.py
Labels: CLA: Yes, Type: Bug - quick
